_commit: v0.43.0
_src_path: gh:kitware-resonant/cookiecutter-resonant
core_app_name: core
include_example_code: false
project_name: ISIC Archive
project_slug: isic
python_package_name: isic
site_domain: api.isic-archive.com
