services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: django
      POSTGRES_PASSWORD: postgres
    ports:
      - ${DOCKER_POSTGRES_PORT-5432}:5432

  elasticsearch:
    image: elasticsearch:7.14.0
    environment:
      ES_JAVA_OPTS: "-Xms250m -Xmx750m"
      discovery.type: single-node
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: elastic
      cluster.routing.allocation.disk.threshold_enabled: "false"
    ports:
      - 9200:9200

  rabbitmq:
    image: rabbitmq:management
    ports:
      - ${DOCKER_RABBITMQ_PORT-5672}:5672
      - ${DOCKER_RABBITMQ_CONSOLE_PORT-15672}:15672

  minio:
    image: minio/minio:latest
    # When run with a TTY, minio prints credentials on startup
    tty: true
    command: ["server", "/data", "--console-address", ":${DOCKER_MINIO_CONSOLE_PORT-9001}"]
    environment:
      MINIO_ROOT_USER: minioAccessKey
      MINIO_ROOT_PASSWORD: minioSecretKey
    ports:
      - ${DOCKER_MINIO_PORT-9000}:9000
      - ${DOCKER_MINIO_CONSOLE_PORT-9001}:9001

  zipstreamer:
    image: ghcr.io/imagemarkup/isic-zipstreamer:master
    environment:
      ZS_LISTFILE_URL_PREFIX: "http://django/api/v2/zip-download/file-listing/?token="
      ZS_LISTFILE_BASIC_AUTH: "insecurezipdownloadauthtoken"
    ports:
      - 4008:4008

  redis:
    image: redis:latest
    ports:
      - ${DOCKER_REDIS_PORT-6379}:6379


  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - ${DOCKER_REDIS_INSIGHT_PORT-5540}:5540
