version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: django
      POSTGRES_PASSWORD: postgres
    ports:
      - ${DOCKER_POSTGRES_PORT-5432}:5432

  elasticsearch:
    image: elasticsearch:7.14.0
    environment:
      ES_JAVA_OPTS: "-Xms250m -Xmx750m"
      discovery.type: single-node
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: elastic
    ports:
      - 9200:9200

  rabbitmq:
    image: rabbitmq:management
    ports:
      - ${DOCKER_RABBITMQ_PORT-5672}:5672

  minio:
    image: minio/minio:latest
    # When run with a TTY, minio prints credentials on startup
    tty: true
    command: ["server", "/data"]
    environment:
      MINIO_ACCESS_KEY: minioAccessKey
      MINIO_SECRET_KEY: minioSecretKey
    ports:
      - ${DOCKER_MINIO_PORT-9000}:9000
