[tox]
min_version = 4.22
requires =
    tox
    tox-uv
envlist =
    lint,
    lint-html,
    test,
    type,
    check-migrations,

[testenv]
package = wheel
pass_env =
    DJANGO_*
dependency_groups =
    dev

[testenv:lockfile]
allowlist_externals = bash
commands = bash generate-requirements.sh

[testenv:lint]
package = skip
dependency_groups = lint
commands =
    ruff check {posargs:.}
    ruff format --check {posargs:.}
    semgrep scan --quiet --config rules.yml --error {posargs:.}

[testenv:lint-html]
package = skip
dependency_groups = lint-html
commands =
    djhtml --check {posargs:isic}

[testenv:type]
# Editable ensures dependencies are installed, but full packaging isn't necessary
package = editable
dependency_groups =
    {[testenv]dependency_groups}
    type
commands =
    mypy {posargs:.}

[testenv:format]
package = skip
dependency_groups = format
allowlist_externals = uv
install_command = uv pip install {opts} {packages}
commands =
    ruff check --fix-only {posargs:.}
    ruff format {posargs:.}

[testenv:format-html]
package = skip
dependency_groups = format-html
commands =
    djhtml {posargs:isic}

[testenv:test]
dependency_groups =
    {[testenv]dependency_groups}
    test
commands =
    pytest {posargs} --cov-report=html --cov-branch --cov=isic

[testenv:check-migrations]
set_env =
    DJANGO_SETTINGS_MODULE=isic.settings.testing
commands =
    {envpython} ./manage.py makemigrations --check --dry-run
