# Generated by Django 5.2.16 on 2026-09-14 12:11

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.lookups
import django_extensions.db.fields
import s3_file_field.fields

import isic.core.storages.utils


class Migration(migrations.Migration):
    replaces = [
        ("studies", "0001_initial"),
        ("studies", "0002_alter_question_type"),
        ("studies", "0003_alter_questionchoice_text"),
        ("studies", "0004_add_multiselect_question_type"),
        ("studies", "0005_alter_annotation_annotator_alter_annotation_image_and_more"),
        ("studies", "0006_add_study_zoomable"),
    ]

    initial = True

    dependencies = [
        ("core", "0001_squashed_0044_image_pin_nonnull"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                (
                    "name",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), size=None
                    ),
                ),
                ("official", models.BooleanField()),
            ],
            options={
                "ordering": ["name"],
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("prompt", models.CharField(max_length=400)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("select", "Select"),
                            ("multiselect", "Multiselect"),
                            ("number", "Number"),
                            ("diagnosis", "Diagnosis"),
                        ],
                        default="select",
                        max_length=11,
                    ),
                ),
                ("official", models.BooleanField()),
            ],
            options={
                "ordering": ["prompt"],
                "get_latest_by": "modified",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("official", True)),
                        fields=("prompt",),
                        name="question_official_prompt_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QuestionChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="studies.question",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
                "unique_together": {("question", "text")},
            },
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("attribution", models.CharField(max_length=200)),
                (
                    "name",
                    models.CharField(
                        help_text="The name for your Study.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A description of the methodology behind your Study.",
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether or not your Study will be public. A study can only be public if the images it uses are also public.",  # noqa: E501
                    ),
                ),
                (
                    "zoomable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether annotators can zoom and pan images while completing tasks. Enabling zoom may confound inter-rater agreement if experts view images at different magnifications.",  # noqa: E501
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        help_text="The Collection of images to use in your Study.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="studies",
                        to="core.collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="studies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(related_name="studies", to="studies.feature"),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        related_name="owned_studies", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Studies",
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("required", models.BooleanField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_questions",
                        to="studies.question",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_questions",
                        to="studies.study",
                    ),
                ),
            ],
            options={
                "unique_together": {("study", "question")},
            },
        ),
        migrations.AddField(
            model_name="study",
            name="questions",
            field=models.ManyToManyField(
                related_name="studies",
                through="studies.StudyQuestion",
                to="studies.question",
            ),
        ),
        migrations.CreateModel(
            name="StudyTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_tasks",
                        to="core.image",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="studies.study",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
                "unique_together": {("study", "annotator", "image")},
            },
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("start_time", models.DateTimeField(null=True)),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annotations",
                        to="core.image",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="studies.study",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="annotation",
                        to="studies.studytask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Markup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "mask",
                    s3_file_field.fields.S3FileField(
                        upload_to=isic.core.storages.utils.generate_upload_to
                    ),
                ),
                ("present", models.BooleanField()),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markups",
                        to="studies.annotation",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markups",
                        to="studies.feature",
                    ),
                ),
            ],
            options={
                "unique_together": {("annotation", "feature")},
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("value", models.JSONField(null=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="studies.annotation",
                    ),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="studies.questionchoice",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="studies.question",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=django.db.models.lookups.Exact(
                            lhs=models.Func(
                                "choice",
                                "value",
                                function="num_nonnulls",
                                output_field=models.IntegerField(),
                            ),
                            rhs=models.Value(1),
                        ),
                        name="response_choice_or_value_check",
                    )
                ],
                "unique_together": {("annotation", "question")},
            },
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_time__lte", models.F("created"))),
                name="annotation_start_time_check",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="annotation",
            unique_together={("study", "task", "image", "annotator")},
        ),
    ]
