# Generated by Django 5.1.2 on 2024-11-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("select", "Select"),
                    ("number", "Number"),
                    ("diagnosis", "Diagnosis"),
                ],
                default="select",
                max_length=9,
            ),
        ),
    ]
