# Generated by Django 3.2 on 2020-10-14 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_add_related_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['prompt']},
        ),
        migrations.AlterField(
            model_name='studytask',
            name='study',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='tasks',
                to='studies.study',
            ),
        ),
    ]
