# Generated by Django 3.1.4 on 2021-01-15 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studies", "0002_add_study_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="annotator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="annotation",
                to="studies.studytask",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="studytask",
            name="annotator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="studytask",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="studies.image"
            ),
        ),
        migrations.AlterField(
            model_name="studytask",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="studies.study",
            ),
        ),
    ]
