# Generated by Django 3.2 on 2021-05-20 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_squashed'),
        ('studies', '0003_auto_20210115_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='image2',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to='core.image'
            ),
        ),
        migrations.AddField(
            model_name='studytask',
            name='image2',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='core.image'
            ),
        ),
    ]
