# Generated by Django 5.2.3 on 2026-04-13 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_alter_collection_creator_and_more"),
        ("studies", "0004_add_multiselect_question_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="annotator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annotations",
                to="core.image",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="choice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="studies.questionchoice",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="studies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="features",
            field=models.ManyToManyField(related_name="studies", to="studies.feature"),
        ),
        migrations.AlterField(
            model_name="study",
            name="questions",
            field=models.ManyToManyField(
                related_name="studies", through="studies.StudyQuestion", to="studies.question"
            ),
        ),
        migrations.AlterField(
            model_name="studyquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="study_questions",
                to="studies.question",
            ),
        ),
        migrations.AlterField(
            model_name="studyquestion",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_questions",
                to="studies.study",
            ),
        ),
        migrations.AlterField(
            model_name="studytask",
            name="annotator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studytask",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_tasks",
                to="core.image",
            ),
        ),
    ]
