# Generated by Django 5.2.3 on 2026-04-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0005_alter_annotation_annotator_alter_annotation_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="zoomable",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether annotators can zoom and pan images while completing tasks. "
                    "Enabling zoom may confound inter-rater agreement if experts view "
                    "images at different magnifications."
                ),
            ),
        ),
    ]
