# Generated by Django 3.2 on 2021-05-20 16:41
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0005_auto_20210520_1637"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
    ]
