# Generated by Django 3.2 on 2021-05-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0008_auto_20210525_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
