# Generated by Django 3.2.9 on 2021-11-28 09:23
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0009_study_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="studies.study",
            ),
        ),
    ]
