# Generated by Django 3.2.9 on 2021-11-29 05:41
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0010_alter_annotation_study"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="StudyQuestion",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "question",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT, to="studies.question"
                            ),
                        ),
                        (
                            "study",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, to="studies.study"
                            ),
                        ),
                    ],
                    options={
                        "db_table": "studies_study_questions",
                        "unique_together": {("study", "question")},
                    },
                ),
                migrations.AlterField(
                    model_name="study",
                    name="questions",
                    field=models.ManyToManyField(
                        through="studies.StudyQuestion", to="studies.Question"
                    ),
                ),
            ]
        )
    ]
