# Generated by Django 3.2.9 on 2021-11-29 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_auto_20211129_0541'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studyquestion',
            table=None,
        ),
    ]
