# Generated by Django 3.2.9 on 2021-11-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_alter_studyquestion_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyquestion',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
