# Generated by Django 3.2.9 on 2021-11-29 06:00

from django.db import migrations
import s3_file_field.fields

import isic.core.storage


class Migration(migrations.Migration):
    dependencies = [
        ('studies', '0013_studyquestion_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='markup',
            name='mask_blob',
            field=s3_file_field.fields.S3FileField(
                null=True, upload_to=isic.core.storage.generate_upload_to
            ),
        ),
    ]
