# Generated by Django 3.2.9 on 2021-11-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0016_remove_markup_mask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markup',
            old_name='mask_blob',
            new_name='mask',
        ),
    ]
