# Generated by Django 3.2.11 on 2022-02-23 01:44

from django.db import migrations


def migrate_question_required(apps, schema_editor):
    StudyQuestion = apps.get_model('studies', 'StudyQuestion')

    for study_question in StudyQuestion.objects.all():
        study_question.required = study_question.question.required
        study_question.save(update_fields=['required'])


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0028_studyquestion_required'),
    ]

    operations = [migrations.RunPython(migrate_question_required)]
