# Generated by Django 4.0.3 on 2022-05-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0031_id_big_auto_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[("select", "Select"), ("number", "Number")], default="select", max_length=6
            ),
        ),
    ]
