# Generated by Django 4.0.3 on 2022-05-25 16:26
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.lookups


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0032_alter_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="value",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="response",
            name="choice",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="studies.questionchoice"
            ),
        ),
        migrations.AddConstraint(
            model_name="response",
            constraint=models.CheckConstraint(
                check=django.db.models.lookups.Exact(
                    lhs=django.db.models.expressions.Func(
                        "choice",
                        "value__value",
                        function="num_nonnulls",
                        output_field=models.IntegerField(),
                    ),
                    rhs=django.db.models.expressions.Value(1),
                ),
                name="response_choice_or_value_check",
            ),
        ),
    ]
