# Generated by Django 4.0.3 on 2022-06-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('studies', '0036_study_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='attribution',
            field=models.CharField(max_length=200),
        ),
    ]
