# Generated by Django 4.1.9 on 2023-06-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0037_alter_study_attribution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="description",
            field=models.TextField(
                blank=True, help_text="A description of the methodology behind your Study."
            ),
        ),
    ]
