# Generated by Django 3.0.8 on 2020-07-22 23:22
from __future__ import annotations

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "girder_id",
                    models.CharField(
                        blank=True,
                        max_length=24,
                        null=True,
                        unique=True,
                        validators=[django.core.validators.RegexValidator("^[0-9a-f]{24}$")],
                    ),
                ),
                ("girder_salt", models.CharField(blank=True, max_length=60, null=True)),
                ("email_verified", models.BooleanField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
