# Generated by Django 5.2.16 on 2026-09-14 12:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import isic.login.models


class Migration(migrations.Migration):
    replaces = [
        ("login", "0001_initial"),
        ("login", "0002_remove_profile_girder_id"),
        ("login", "0003_alter_profile_hash_id"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash_id",
                    models.CharField(
                        default=isic.login.models._generate_random_hashid,  # noqa: SLF001
                        max_length=5,
                        unique=True,
                        validators=[django.core.validators.RegexValidator("^[A-HJ-NP-Z2-9]{5}$")],
                    ),
                ),
                ("accepted_terms", models.DateTimeField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
