# Generated by Django 5.1.11 on 2025-06-20 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="girder_id",
        ),
    ]
