# Generated by Django 3.2.3 on 2021-06-02 09:24
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_merge_default_site"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email_verified",
        ),
    ]
