# Generated by Django 5.2.3 on 2026-05-27 19:02

import django.core.validators
from django.db import migrations, models

import isic.login.models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_remove_profile_girder_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="hash_id",
            field=models.CharField(
                default=isic.login.models._generate_random_hashid,  # noqa: SLF001
                max_length=5,
                unique=True,
                validators=[django.core.validators.RegexValidator("^[A-HJ-NP-Z2-9]{5}$")],
            ),
        ),
    ]
