# Generated by Django 3.2.9 on 2021-12-14 18:58
from __future__ import annotations

import django.core.validators
from django.db import migrations, models

from isic.login.models import get_hashid


def gen_hashid(apps, schema_editor):
    Profile = apps.get_model("login", "Profile")

    for row in Profile.objects.all():
        row.hash_id = get_hashid(row.user.pk)
        row.save()


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0004_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hash_id",
            field=models.CharField(
                max_length=5,
                null=True,
                unique=True,
                validators=[django.core.validators.RegexValidator("^[A-HJ-NP-Z2-9]{5}")],
            ),
        ),
        migrations.RunPython(gen_hashid),
    ]
