# Generated by Django 3.2.9 on 2021-12-14 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_profile_hash_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hash_id',
            field=models.CharField(
                max_length=5,
                unique=True,
                validators=[django.core.validators.RegexValidator('^[A-HJ-NP-Z2-9]{5}')],
            ),
        ),
    ]
