# Generated by Django 3.2.11 on 2022-01-16 07:06
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0006_alter_profile_hash_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="accepted_terms",
            field=models.DateTimeField(null=True),
        ),
    ]
