# Generated by Django 4.0.3 on 2022-04-01 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_id_big_auto_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hash_id',
            field=models.CharField(
                max_length=5,
                unique=True,
                validators=[django.core.validators.RegexValidator('^[A-HJ-NP-Z2-9]{5}$')],
            ),
        ),
    ]
