# Generated by Django 4.0.3 on 2022-06-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_profile_hash_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='girder_salt',
        ),
    ]
