---
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgres:latest-ram
        environment:
          POSTGRES_DB: django
          POSTGRES_PASSWORD: postgres
      - image: minio/minio:latest
        command: server /data
        environment:
          MINIO_ACCESS_KEY: minioAccessKey
          MINIO_SECRET_KEY: minioSecretKey
    steps:
      - run:
          name: Install Git LFS
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
      - checkout
      - run:
          name: Install tox
          command: sudo pip install tox
      - run:
          name: Run tests
          command: tox
          environment:
            DJANGO_DATABASE_URL: postgres://postgres:postgres@localhost:5432/django
            DJANGO_MINIO_STORAGE_ENDPOINT: localhost:9000
            DJANGO_MINIO_STORAGE_ACCESS_KEY: minioAccessKey
            DJANGO_MINIO_STORAGE_SECRET_KEY: minioSecretKey
workflows:
  version: 2
  ci:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
