---
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgres:12-alpine-ram
    steps:
      - checkout
      - run:
          name: Install tox
          command: sudo pip install tox
      - run:
          name: Run tests
          command: tox
workflows:
  version: 2
  ci:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
