# Generated by Django 5.2.16 on 2026-09-14 12:11

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    replaces = [
        ("stats", "0001_initial"),
        ("stats", "0002_lastenqueueds3log"),
        ("stats", "0003_alter_lastenqueueds3log_name"),
        ("stats", "0004_searchquery"),
        ("stats", "0005_remove_searchquery"),
    ]

    initial = True

    dependencies = [
        ("core", "0001_squashed_0044_image_pin_nonnull"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastEnqueuedS3Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GaMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("range_start", models.DateTimeField()),
                ("range_end", models.DateTimeField()),
                ("num_sessions", models.PositiveIntegerField()),
                ("sessions_per_country", models.JSONField()),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("range_start__lt", models.F("range_end"))),
                        name="range_end_gt_range_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ImageDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
                ),
                ("download_time", models.DateTimeField()),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(max_length=400, null=True)),
                ("request_id", models.CharField(max_length=200)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="downloads",
                        to="core.image",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("download_time__lt", models.F("created"))),
                        name="download_occurred_before_tracking",
                    ),
                    models.UniqueConstraint(fields=("request_id",), name="unique_request_id"),
                ],
            },
        ),
    ]
