# Generated by Django 5.1.1 on 2024-09-30 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastEnqueuedS3Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=36,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}-(\\d{2}-){5}[A-F0-9]{16}$"
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
