# Generated by Django 5.1.1 on 2024-09-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0002_lastenqueueds3log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lastenqueueds3log",
            name="name",
            field=models.CharField(unique=True),
        ),
    ]
