# Generated by Django 3.2.11 on 2022-03-06 09:02

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_imagedownload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagedownload',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterField(
            model_name='gametrics',
            name='num_sessions',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='gametrics',
            constraint=models.CheckConstraint(
                check=models.Q(('range_start__lt', django.db.models.expressions.F('range_end'))),
                name='range_end_gt_range_start',
            ),
        ),
        migrations.AddConstraint(
            model_name='imagedownload',
            constraint=models.CheckConstraint(
                check=models.Q(('download_time__lt', django.db.models.expressions.F('created'))),
                name='download_occurred_before_tracking',
            ),
        ),
    ]
