# Generated by Django 4.0.3 on 2022-03-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_id_big_auto_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedownload',
            name='user_agent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
