# Generated by Django 5.2.3 on 2025-10-30 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0004_searchquery"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SearchQuery",
        ),
    ]
