# Generated by Django 5.2.16 on 2026-09-14 12:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    replaces = [
        ("engagement", "0001_initial"),
        ("engagement", "0002_emaildomaincontributor"),
        ("engagement", "0003_alter_engagementprofile_default_cohort_and_more"),
        ("engagement", "0004_engagementaccession"),
    ]

    initial = True

    dependencies = [
        ("ingest", "0001_squashed_0043_alter_rcmcase_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDomainContributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, db_index=True
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="The email domain, e.g. mskcc.org.",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid domain, e.g. mskcc.org.",
                                regex="^[a-zA-Z0-9]([a-zA-Z0-9\\-]*[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9\\-]*[a-zA-Z0-9])?)+$",
                            )
                        ],
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_domains",
                        to="ingest.contributor",
                    ),
                ),
            ],
            options={
                "ordering": ["domain"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EngagementAccession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="The engagement platform's own identifier for this image.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "accession",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement",
                        to="ingest.accession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EngagementProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "default_cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="engagement_profiles",
                        to="ingest.cohort",
                    ),
                ),
                (
                    "default_contributor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="engagement_profiles",
                        to="ingest.contributor",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("default_cohort__isnull", True),
                            ("default_contributor__isnull", False),
                            _connector="OR",
                        ),
                        name="engagement_profile_cohort_implies_contributor",
                    )
                ],
            },
        ),
    ]
