# Generated by Django 5.2.16 on 2026-08-03 19:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("engagement", "0001_initial"),
        ("ingest", "0043_alter_rcmcase_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDomainContributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, db_index=True
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="The email domain, e.g. mskcc.org.",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid domain, e.g. mskcc.org.",
                                regex="^[a-zA-Z0-9]([a-zA-Z0-9\\-]*[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9\\-]*[a-zA-Z0-9])?)+$",
                            )
                        ],
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_domains",
                        to="ingest.contributor",
                    ),
                ),
            ],
            options={
                "ordering": ["domain"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
    ]
