# Generated by Django 5.2.16 on 2026-08-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("engagement", "0002_emaildomaincontributor"),
        ("ingest", "0043_alter_rcmcase_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engagementprofile",
            name="default_cohort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="engagement_profiles",
                to="ingest.cohort",
            ),
        ),
        migrations.AlterField(
            model_name="engagementprofile",
            name="default_contributor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="engagement_profiles",
                to="ingest.contributor",
            ),
        ),
    ]
