# Generated by Django 5.2.16 on 2026-08-12 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("engagement", "0003_alter_engagementprofile_default_cohort_and_more"),
        ("ingest", "0043_alter_rcmcase_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EngagementAccession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="The engagement platform's own identifier for this image.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "accession",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement",
                        to="ingest.accession",
                    ),
                ),
            ],
        ),
    ]
