# Generated by Django 5.2.16 on 2026-09-14 12:11

from django.conf import settings
import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
import django.core.validators
from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.math
import django.utils.timezone
import django_extensions.db.fields
import isic_metadata.fields
import s3_file_field.fields

import isic.ingest.models.accession
import isic.ingest.models.lesion
import isic.ingest.models.patient
import isic.ingest.models.rcm_case
import isic.ingest.utils.json


class Migration(migrations.Migration):
    replaces = [
        ("ingest", "0001_initial_squashed_0032_alter_metadataversion_created_and_more"),
        ("ingest", "0033_alter_distinctnessmeasure_options_and_more"),
        ("ingest", "0034_alter_distinctnessmeasure_options_and_more"),
        ("ingest", "0035_alter_distinctnessmeasure_checksum"),
        ("ingest", "0036_add_anatom_site_hierarchical_fields"),
        ("ingest", "0037_publishrequest_default_attribution"),
        ("ingest", "0038_alter_accessionreview_creator_and_more"),
        ("ingest", "0039_drop_anatom_site_general"),
        ("ingest", "0040_remove_accession_accession_lesion_id_patient_id_exclusion_and_more"),
        ("ingest", "0041_accession_accession_lesion_id_patient_id_exclusion_and_more"),
        ("ingest", "0042_blob_verbose_names"),
        ("ingest", "0043_alter_rcmcase_id"),
    ]

    initial = True

    dependencies = [
        ("core", "0001_squashed_0044_image_pin_nonnull"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name="Accession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, db_index=True
                    ),
                ),
                ("concomitant_biopsy", models.BooleanField(blank=True, null=True)),
                (
                    "fitzpatrick_skin_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("sex", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "anatom_site_special",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "anatom_site_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "anatom_site_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "anatom_site_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "anatom_site_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "anatom_site_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "diagnosis_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "diagnosis_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "diagnosis_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "diagnosis_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "diagnosis_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "diagnosis_confirm_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("personal_hx_mm", models.BooleanField(blank=True, null=True)),
                ("family_hx_mm", models.BooleanField(blank=True, null=True)),
                (
                    "clin_size_long_diam_mm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("melanocytic", models.BooleanField(blank=True, null=True)),
                (
                    "mel_mitotic_index",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mel_thick_mm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("mel_ulcer", models.BooleanField(blank=True, null=True)),
                ("acquisition_day", models.IntegerField(blank=True, null=True)),
                (
                    "image_manipulation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("image_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dermoscopic_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tbp_tile_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "girder_id",
                    models.CharField(
                        blank=True, help_text="The image_id from Girder.", max_length=24
                    ),
                ),
                (
                    "copyright_license",
                    models.CharField(
                        choices=[
                            ("CC-0", "CC-0"),
                            ("CC-BY", "CC-BY"),
                            ("CC-BY-NC", "CC-BY-NC"),
                        ],
                        max_length=255,
                    ),
                ),
                ("attribution", models.CharField(blank=True, max_length=200)),
                ("original_blob", s3_file_field.fields.S3FileField(unique=True)),
                (
                    "original_blob_name",
                    models.CharField(editable=False, max_length=255),
                ),
                ("original_blob_size", models.PositiveBigIntegerField(editable=False)),
                ("blob", s3_file_field.fields.S3FileField(blank=True)),
                (
                    "sponsored_blob",
                    models.FileField(
                        blank=True,
                        storage=isic.ingest.models.accession.sponsored_blob_storage,
                        upload_to="images/",
                    ),
                ),
                (
                    "blob_size",
                    models.PositiveBigIntegerField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("is_cog", models.BooleanField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "Creating"),
                            ("created", "Created"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                            ("succeeded", "Succeeded"),
                        ],
                        default="creating",
                        max_length=20,
                    ),
                ),
                ("thumbnail_256", s3_file_field.fields.S3FileField(blank=True)),
                (
                    "sponsored_thumbnail_256_blob",
                    models.FileField(
                        blank=True,
                        storage=isic.ingest.models.accession.sponsored_blob_storage,
                        upload_to="thumbnails/",
                    ),
                ),
                (
                    "thumbnail_256_size",
                    models.PositiveIntegerField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccessionReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("value", models.BooleanField()),
                (
                    "accession",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="ingest.accession",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="accession_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at"],
                "get_latest_by": "reviewed_at",
            },
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, db_index=True
                    ),
                ),
                (
                    "girder_id",
                    models.CharField(
                        blank=True,
                        help_text="The dataset_id from Girder.",
                        max_length=24,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of your Cohort. <strong>This is private</strong>, and will not be published along with your images.",  # noqa: E501
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text='The description of your Cohort. <strong>This is private</strong>, and will not be published along with your images. Supports <a href="https://www.markdownguide.org/cheat-sheet/">markdown</a>.'  # noqa: E501
                    ),
                ),
                (
                    "default_copyright_license",
                    models.CharField(
                        choices=[
                            ("CC-0", "CC-0"),
                            ("CC-BY", "CC-BY"),
                            ("CC-BY-NC", "CC-BY-NC"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "default_attribution",
                    models.CharField(
                        help_text="The institution name that should be attributed.",
                        max_length=200,
                    ),
                ),
                (
                    "collection",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cohort",
                        to="core.collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cohorts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="accession",
            name="cohort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accessions",
                to="ingest.cohort",
            ),
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, db_index=True
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        help_text="The full name of your affiliated institution. <strong>This is private</strong>, and will not be published along with your images.",  # noqa: E501
                        max_length=255,
                        verbose_name="Institution Name",
                    ),
                ),
                (
                    "institution_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL of your affiliated institution. <strong>This is private</strong>, and will not be published along with your images.",  # noqa: E501
                        verbose_name="Institution URL",
                    ),
                ),
                (
                    "legal_contact_info",
                    models.TextField(
                        help_text="The person or institution responsible for legal inquiries about your data. <strong>This is private</strong>, and will not be published along with your images.",  # noqa: E501
                        verbose_name="Legal Contact Information",
                    ),
                ),
                (
                    "default_copyright_license",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CC-0", "CC-0"),
                            ("CC-BY", "CC-BY"),
                            ("CC-BY-NC", "CC-BY-NC"),
                        ],
                        max_length=255,
                        verbose_name="Default Copyright License",
                    ),
                ),
                (
                    "default_attribution",
                    models.CharField(
                        blank=True,
                        help_text="Text which must be reproduced by users of your images, to comply with Creative Commons Attribution requirements.",  # noqa: E501
                        max_length=255,
                        verbose_name="Default Attribution",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_contributors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        related_name="owned_contributors", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cohort",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cohorts",
                to="ingest.contributor",
            ),
        ),
        migrations.CreateModel(
            name="DistinctnessMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "checksum",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        validators=[django.core.validators.RegexValidator("^[0-9a-f]{64}$")],
                    ),
                ),
                (
                    "accession",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ingest.accession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesion",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=isic.ingest.models.lesion._default_id,  # noqa: SLF001
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator("^IL_[0-9]{7}$")],
                    ),
                ),
                ("private_lesion_id", models.CharField(max_length=255)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesions",
                        to="ingest.cohort",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accession",
            name="lesion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accessions",
                to="ingest.lesion",
            ),
        ),
        migrations.CreateModel(
            name="MetadataFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, db_index=True
                    ),
                ),
                (
                    "blob",
                    s3_file_field.fields.S3FileField(
                        unique=True,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["csv"]
                            )
                        ],
                        verbose_name="CSV file",
                    ),
                ),
                ("blob_name", models.CharField(editable=False, max_length=255)),
                ("blob_size", models.PositiveBigIntegerField(editable=False)),
                ("validation_errors", models.TextField(blank=True)),
                ("validation_completed", models.BooleanField(default=False)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_files",
                        to="ingest.cohort",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BulkMetadataApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField(blank=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_metadata_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "metadata_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metadata_applications",
                        to="ingest.metadatafile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetadataVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "metadata",
                    models.JSONField(encoder=isic.ingest.utils.json.DecimalAwareJSONEncoder),
                ),
                ("unstructured_metadata", models.JSONField()),
                ("lesion", models.JSONField(default=dict)),
                ("patient", models.JSONField(default=dict)),
                ("rcm_case", models.JSONField(default=dict)),
                (
                    "accession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="metadata_versions",
                        to="ingest.accession",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="metadata_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "get_latest_by": "created",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=isic.ingest.models.patient._default_id,  # noqa: SLF001
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator("^IP_[0-9]{7}$")],
                    ),
                ),
                ("private_patient_id", models.CharField(max_length=255)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="ingest.cohort",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accession",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accessions",
                to="ingest.patient",
            ),
        ),
        migrations.CreateModel(
            name="PublishRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("public", models.BooleanField(default=False)),
                ("default_attribution", models.CharField(default="", max_length=200)),
                ("collections", models.ManyToManyField(to="core.collection")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publish_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublishRequestAccession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accession",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingest.accession",
                    ),
                ),
                (
                    "publish_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publish_request_accessions",
                        to="ingest.publishrequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="publishrequest",
            name="accessions",
            field=models.ManyToManyField(
                through="ingest.PublishRequestAccession", to="ingest.accession"
            ),
        ),
        migrations.CreateModel(
            name="RcmCase",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=isic.ingest.models.rcm_case._default_id,  # noqa: SLF001
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("private_rcm_case_id", models.CharField(max_length=255)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rcm_cases",
                        to="ingest.cohort",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accession",
            name="rcm_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accessions",
                to="ingest.rcmcase",
            ),
        ),
        migrations.CreateModel(
            name="UnstructuredMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.JSONField(blank=True, default=dict)),
                (
                    "accession",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unstructured_metadata",
                        to="ingest.accession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZipUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, db_index=True
                    ),
                ),
                (
                    "blob",
                    s3_file_field.fields.S3FileField(
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["zip"]
                            )
                        ],
                        verbose_name="zip file",
                    ),
                ),
                ("blob_name", models.CharField(editable=False, max_length=255)),
                ("blob_size", models.PositiveBigIntegerField(editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("extracting", "Extracting"),
                            ("extracted", "Extracted"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "fail_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("duplicates", "Duplicates"),
                            ("invalid", "Invalid"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zip_uploads",
                        to="ingest.cohort",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zip_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="accession",
            name="zip_upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accessions",
                to="ingest.zipupload",
            ),
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.UniqueConstraint(
                condition=models.Q(("girder_id", ""), _negated=True),
                fields=("girder_id",),
                name="cohort_unique_girder_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesion",
            constraint=models.UniqueConstraint(
                fields=("private_lesion_id", "cohort"), name="unique_lesion"
            ),
        ),
        migrations.AddConstraint(
            model_name="lesion",
            constraint=models.CheckConstraint(
                condition=models.Q(("id__regex", "^IL_[0-9]{7}$")),
                name="lesion_id_valid_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="metadatafile",
            constraint=models.CheckConstraint(
                condition=models.Q(("blob", ""), _negated=True), name="blob_not_empty"
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                fields=("private_patient_id", "cohort"), name="unique_patient"
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.CheckConstraint(
                condition=models.Q(("id__regex", "^IP_[0-9]{7}$")),
                name="patient_id_valid_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="rcmcase",
            constraint=models.UniqueConstraint(
                fields=("private_rcm_case_id", "cohort"), name="unique_rcm_case"
            ),
        ),
        migrations.AddConstraint(
            model_name="zipupload",
            constraint=models.UniqueConstraint(
                condition=models.Q(("blob", ""), _negated=True),
                fields=("blob",),
                name="zipupload_unique_blob",
            ),
        ),
        migrations.AddConstraint(
            model_name="zipupload",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "failed"),
                        models.Q(("fail_reason", ""), _negated=True),
                    ),
                    models.Q(("status", "failed"), _negated=True),
                    _connector="OR",
                ),
                name="zipupload_fail_reason_requires_failed_status",
            ),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(
                fields=["lesion_id", "id", "cohort_id"],
                name="ingest_acce_lesion__f2701b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(
                fields=["cohort_id", "status", "created"],
                name="ingest_acce_cohort__e73c08_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(
                fields=["original_blob_name"], name="ingest_acce_origina_23620f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(fields=["girder_id"], name="ingest_acce_girder__d68973_idx"),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(
                django.db.models.functions.comparison.Cast(
                    django.db.models.expressions.CombinedExpression(
                        django.db.models.functions.math.Round(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.functions.comparison.Cast(
                                    "age", output_field=models.FloatField()
                                ),
                                "/",
                                models.Value(5.0),
                            )
                        ),
                        "*",
                        models.Value(5),
                    ),
                    output_field=models.IntegerField(),
                ),
                name="accession_rounded_age",
            ),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(
                fields=["fitzpatrick_skin_type"], name="ingest_acce_fitzpat_15c454_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(
                condition=models.Q(("diagnosis_1", "Benign"), _negated=True),
                fields=["diagnosis_1"],
                name="accession_diagnosis_1",
            ),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(fields=["diagnosis_2"], name="accession_diagnosis_2"),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(fields=["diagnosis_3"], name="accession_diagnosis_3"),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(fields=["diagnosis_4"], name="accession_diagnosis_4"),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(fields=["diagnosis_5"], name="accession_diagnosis_5"),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(
                fields=["image_manipulation"], name="ingest_acce_image_m_aee960_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(fields=["mel_mitotic_index"], name="ingest_acce_mel_mit_261415_idx"),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(fields=["mel_ulcer"], name="ingest_acce_mel_ulc_d11b54_idx"),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(
                condition=models.Q(
                    ("image_type__in", ["TBP tile: close-up", "dermoscopic"]),
                    _negated=True,
                ),
                fields=["image_type"],
                name="accession_image_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("girder_id", ""), _negated=True),
                fields=("girder_id",),
                name="accession_unique_girder_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("blob", ""), _negated=True),
                fields=("blob",),
                name="accession_unique_blob",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sponsored_blob", ""), _negated=True),
                fields=("sponsored_blob",),
                name="accession_unique_sponsored_blob",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sponsored_thumbnail_256_blob", ""), _negated=True),
                fields=("sponsored_thumbnail_256_blob",),
                name="accession_unique_sponsored_thumbnail_256_blob",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.CheckConstraint(
                condition=models.Q(("blob", ""), ("sponsored_blob", ""), _connector="OR"),
                name="accession_blob_or_sponsored_blob",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sponsored_blob", ""), _negated=True),
                    ("sponsored_thumbnail_256_blob", ""),
                    _connector="OR",
                ),
                name="accession_sponsored_blob_implies_sponsored_thumbnail_256_blob",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("blob_size__isnull", False),
                        ("height__isnull", False),
                        ("status", "succeeded"),
                        ("thumbnail_256_size__isnull", False),
                        ("width__isnull", False),
                    ),
                    models.Q(("status", "succeeded"), _negated=True),
                    _connector="OR",
                ),
                name="accession_succeeded_blob_fields",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("concomitant_biopsy", True),
                        ("diagnosis_confirm_type", "histopathology"),
                    ),
                    models.Q(("concomitant_biopsy", True), _negated=True),
                    _connector="OR",
                ),
                name="accession_concomitant_biopsy_diagnosis_confirm_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("lesion_id__isnull", False), ("patient_id__isnull", False)),
                deferrable=django.db.models.constraints.Deferrable["IMMEDIATE"],
                expressions=[("lesion_id", "="), ("patient_id", "<>")],
                name="accession_lesion_id_patient_id_exclusion",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("rcm_case_id__isnull", False), ("lesion_id__isnull", False)),
                deferrable=django.db.models.constraints.Deferrable["IMMEDIATE"],
                expressions=[("rcm_case_id", "="), ("lesion_id", "<>")],
                name="accession_rcm_case_id_lesion_id_exclusion",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "image_type",
                        isic_metadata.fields.ImageTypeEnum["rcm_macroscopic"],
                    )
                ),
                fields=("cohort_id", "rcm_case_id"),
                name="accession_unique_rcm_case_id_macroscopic_image",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_cog", False),
                    ("image_type__isnull", True),
                    ("image_type", isic_metadata.fields.ImageTypeEnum["rcm_mosaic"]),
                    _connector="OR",
                ),
                name="accession_is_cog_mosaic",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accession",
            unique_together={("cohort", "original_blob_name")},
        ),
    ]
