# Generated by Django 3.1.4 on 2020-12-25 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadblob',
            name='upload',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='blobs',
                to='upload.upload',
            ),
        ),
    ]
