# Generated by Django 3.1.4 on 2021-01-19 20:17

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zip',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created'),
                    ('extracting', 'Extracting'),
                    ('extracted', 'Extracted'),
                ],
                default='created',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='Accession',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                (
                    'blob',
                    s3_file_field.fields.S3FileField(
                        max_length=2000,
                        upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename,
                    ),
                ),
                ('blob_name', models.CharField(max_length=255)),
                ('blob_size', models.PositiveBigIntegerField()),
                (
                    'status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('skipped', 'Skipped'),
                            ('failed', 'Failed'),
                            ('succeeded', 'Succeeded'),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    'review_status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('ignored', 'Ignored'),
                            ('rejected', 'Rejected'),
                            ('accepted', 'Accepted'),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ('sha1', models.CharField(max_length=40)),
                (
                    'upload',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='accessions',
                        to='ingest.zip',
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
