# Generated by Django 4.2.13 on 2024-07-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accession",
            name="is_cog",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
