# Generated by Django 3.1.4 on 2021-01-19 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_auto_20210119_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accession',
            name='sha1',
        ),
        migrations.AddField(
            model_name='accession',
            name='checksum',
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')],
            ),
        ),
    ]
