# Generated by Django 3.1.4 on 2021-01-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_auto_20210119_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='status',
            field=models.CharField(
                choices=[
                    ('creating', 'Creating'),
                    ('created', 'Created'),
                    ('skipped', 'Skipped'),
                    ('failed', 'Failed'),
                    ('succeeded', 'Succeeded'),
                ],
                default='creating',
                max_length=20,
            ),
        ),
    ]
