# Generated by Django 4.0.3 on 2022-03-29 01:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingest', '0003_metadatarevision'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetadataRevision',
            new_name='MetadataVersion',
        ),
    ]
