# Generated by Django 5.1.1 on 2024-10-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0004_remove_accession_accession_is_cog_mosaic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accession",
            name="legacy_dx",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
