# Generated by Django 3.1.4 on 2021-01-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_distinctnessmeasure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accession',
            name='checksum',
        ),
    ]
