# Generated by Django 4.0.3 on 2022-04-16 19:24

from django.db import migrations


def migrate_checks(apps, schema_editor):
    Accession = apps.get_model('ingest', 'Accession')  # noqa: N806
    User = apps.get_model('auth', 'User')  # noqa: N806
    checks = ['quality_check', 'diagnosis_check', 'phi_check', 'duplicate_check', 'lesion_check']

    for i, accession in enumerate(Accession.objects.iterator()):
        if i % 10_000 == 0:
            print(i)
        check_values = [getattr(accession, check) for check in checks]
        failed_review = False in check_values
        unreviewed = set(check_values) == {None}
        fully_passed_review = set(check_values) == {True}
        partially_passed_review = not failed_review and not unreviewed and not fully_passed_review

        if failed_review:
            if accession.pk == 4491:  # broken accession with no checklogs
                accession.checklogs.create(
                    creator=User.objects.get(pk=8), change_field='quality_check', change_to=False
                )
            else:
                first_failed_checklog = accession.checklogs.filter(change_to=False).earliest()
                accession.checklogs.exclude(pk=first_failed_checklog.pk).delete()
        elif unreviewed:
            accession.checklogs.all().delete()
        elif fully_passed_review:
            last_passed_checklog = accession.checklogs.latest()
            accession.checklogs.exclude(pk=last_passed_checklog.pk).delete()
        elif partially_passed_review:
            if hasattr(accession, 'image'):  # published
                last_passed_checklog = accession.checklogs.filter(change_to=True).latest()
                accession.checklogs.exclude(pk=last_passed_checklog.pk).delete()
            else:
                # unpublished, some passed checks.
                # that isn't exhaustive, so reset everything.
                accession.checklogs.all().delete()
        else:
            raise Exception(f'unexpected state for accession {accession.pk}.')


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0007_auto_20220413_1820'),
    ]

    operations = [
        migrations.RunPython(migrate_checks),
    ]
