# Generated by Django 3.1.4 on 2021-01-23 01:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0007_auto_20210123_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='accession',
            name='unstructured_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
