# Generated by Django 4.0.3 on 2022-04-16 20:32
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0008_auto_20220416_1924"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checklog",
            old_name="change_to",
            new_name="value",
        ),
        migrations.RemoveField(
            model_name="checklog",
            name="change_field",
        ),
        migrations.AlterField(
            model_name="checklog",
            name="accession",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checklogs",
                to="ingest.accession",
            ),
        ),
    ]
