# Generated by Django 3.1.4 on 2021-01-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0008_auto_20210123_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='accession',
            name='unstructured_metadata',
            field=models.JSONField(default=dict),
        ),
    ]
