# Generated by Django 4.0.3 on 2022-04-16 20:32
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0009_rename_change_to_checklog_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklog",
            name="value",
            field=models.BooleanField(),
        ),
    ]
