# Generated by Django 5.1.2 on 2024-10-16 18:06

from django.db import migrations, models


def migrate_diagnoses(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE ingest_accession
            SET diagnosis_1 = NULLIF(SPLIT_PART(diagnosis, ':', 1), ''),
                diagnosis_2 = NULLIF(SPLIT_PART(diagnosis, ':', 2), ''),
                diagnosis_3 = NULLIF(SPLIT_PART(diagnosis, ':', 3), ''),
                diagnosis_4 = NULLIF(SPLIT_PART(diagnosis, ':', 4), ''),
                diagnosis_5 = NULLIF(SPLIT_PART(diagnosis, ':', 5), '')
            WHERE diagnosis IS NOT NULL
            """
        )


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0009_accession_accession_diagnosis_gin"),
    ]

    operations = [
        migrations.AddField(
            model_name="accession",
            name="diagnosis_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accession",
            name="diagnosis_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accession",
            name="diagnosis_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accession",
            name="diagnosis_4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accession",
            name="diagnosis_5",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(migrate_diagnoses),
    ]
