# Generated by Django 3.1.4 on 2021-01-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0009_auto_20210123_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='blob_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
