# Generated by Django 4.0.3 on 2022-04-16 20:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ingest", "0010_alter_checklog_value"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CheckLog",
            new_name="AccessionReview",
        ),
    ]
