# Generated by Django 5.1.2 on 2024-10-16 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0010_accession_diagnosis_1_accession_diagnosis_2_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accession",
            name="valid_diagnosis",
        ),
        migrations.RemoveIndex(
            model_name="accession",
            name="accession_diagnosis",
        ),
        migrations.RemoveIndex(
            model_name="accession",
            name="accession_diagnosis_gin",
        ),
        migrations.RemoveField(
            model_name="accession",
            name="diagnosis",
        ),
    ]
