# Generated by Django 3.1.4 on 2021-01-27 22:44

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0010_auto_20210123_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataFile',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('blob', s3_file_field.fields.S3FileField()),
                ('blob_name', models.CharField(max_length=255)),
                ('blob_size', models.PositiveBigIntegerField()),
                (
                    'cohort',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='metadata_files',
                        to='ingest.cohort',
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
