# Generated by Django 4.0.3 on 2022-04-16 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0011_rename_checklog_accessionreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessionreview',
            name='accession',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='review',
                to='ingest.accession',
            ),
        ),
    ]
