# Generated by Django 5.1.2 on 2024-10-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0011_remove_accession_valid_diagnosis_and_more"),
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(
                condition=models.Q(("diagnosis_1", "Benign"), _negated=True),
                fields=["diagnosis_1"],
                name="accession_diagnosis_1",
            ),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(fields=["diagnosis_2"], name="accession_diagnosis_2"),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(fields=["diagnosis_3"], name="accession_diagnosis_3"),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(fields=["diagnosis_4"], name="accession_diagnosis_4"),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(fields=["diagnosis_5"], name="accession_diagnosis_5"),
        ),
    ]
