# Generated by Django 5.1.3 on 2024-11-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0012_accession_accession_diagnosis_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accession",
            name="anatom_site_special",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
