# Generated by Django 3.1.4 on 2021-01-27 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingest', '0012_auto_20210127_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatafile',
            name='creator',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'
            ),
            preserve_default=False,
        ),
    ]
