# Generated by Django 3.1.4 on 2021-01-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0013_metadatafile_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='review_status',
            field=models.CharField(
                blank=True,
                choices=[('rejected', 'Rejected'), ('accepted', 'Accepted')],
                max_length=20,
                null=True,
            ),
        ),
    ]
