# Generated by Django 4.0.3 on 2022-04-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ingest', '0013_remove_accession_diagnosis_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessionreview',
            name='reviewed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
