# Generated by Django 5.1.3 on 2024-12-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0013_accession_anatom_site_special"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="description",
            field=models.TextField(
                help_text='The description of your Cohort.<strong>This is private</strong>, and will not be published along with your images.<br />Supports <a href="https://www.markdownguide.org/cheat-sheet/">markdown</a>.'  # noqa: E501
            ),
        ),
    ]
