# Generated by Django 3.1.4 on 2021-02-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0014_auto_20210129_0456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accession',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='accession',
            unique_together={('upload', 'blob_name')},
        ),
    ]
