# Generated by Django 5.1.7 on 2025-03-24 15:39

import django.contrib.postgres.constraints
from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0015_bulkmetadataapplication"),
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accession",
            name="accession_lesion_id_patient_id_exclusion",
        ),
        migrations.RemoveConstraint(
            model_name="accession",
            name="accession_rcm_case_id_lesion_id_exclusion",
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("lesion_id__isnull", False), ("patient_id__isnull", False)),
                deferrable=django.db.models.constraints.Deferrable["IMMEDIATE"],
                expressions=[("lesion_id", "="), ("patient_id", "<>")],
                name="accession_lesion_id_patient_id_exclusion",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("rcm_case_id__isnull", False), ("lesion_id__isnull", False)),
                deferrable=django.db.models.constraints.Deferrable["IMMEDIATE"],
                expressions=[("rcm_case_id", "="), ("lesion_id", "<>")],
                name="accession_rcm_case_id_lesion_id_exclusion",
            ),
        ),
    ]
