# Generated by Django 3.1.4 on 2021-02-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0015_auto_20210203_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='reject_reason',
            field=models.CharField(
                blank=True,
                choices=[
                    ('low_quality', 'Low Quality'),
                    ('duplicate', 'Duplicate'),
                    ('has_phi', 'Has PHI'),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
