# Generated by Django 4.0.3 on 2022-04-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ingest', '0015_auto_20220417_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessionreview',
            name='reviewed_at',
            field=models.DateTimeField(),
        ),
    ]
