# Generated by Django 5.1.7 on 2025-03-31 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0016_remove_accession_accession_lesion_id_patient_id_exclusion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkmetadataapplication",
            name="metadata_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metadata_applications",
                to="ingest.metadatafile",
            ),
        ),
    ]
