# Generated by Django 3.1.4 on 2021-02-08 00:46

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0016_accession_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='original_blob',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
    ]
