# Generated by Django 3.1.4 on 2021-02-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0017_accession_original_blob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accession',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='accession',
            name='review_status',
        ),
        migrations.AddField(
            model_name='accession',
            name='diagnosis_check',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='accession',
            name='duplicate_check',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='accession',
            name='lesion_check',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='accession',
            name='phi_check',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='accession',
            name='quality_check',
            field=models.BooleanField(null=True),
        ),
    ]
