# Generated by Django 5.1.7 on 2025-04-01 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0017_alter_bulkmetadataapplication_metadata_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cohort",
            old_name="attribution",
            new_name="default_attribution",
        ),
    ]
