# Generated by Django 5.1.7 on 2025-04-01 15:18

from django.db import migrations, models


def set_attribution_from_cohort(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
                UPDATE ingest_accession
                SET attribution = cohort.default_attribution
                FROM ingest_cohort AS cohort
                WHERE ingest_accession.cohort_id = cohort.id
            """)


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0018_rename_attribution_cohort_default_attribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="accession",
            name="attribution",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.RunPython(set_attribution_from_cohort, elidable=True),
        migrations.AlterField(
            model_name="accession",
            name="attribution",
            field=models.CharField(max_length=200),
        ),
    ]
