# Generated by Django 3.1.4 on 2021-02-23 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingest', '0018_auto_20210208_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='attribution',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cohort',
            name='copyright_license',
            field=models.CharField(
                choices=[('CC-0', 'CC-0'), ('CC-BY', 'CC-BY'), ('CC-BY-NC', 'CC-BY-NC')],
                default='',
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_url', models.URLField()),
                ('legal_contact_info', models.TextField()),
                (
                    'default_copyright_license',
                    models.CharField(
                        choices=[('CC-0', 'CC-0'), ('CC-BY', 'CC-BY'), ('CC-BY-NC', 'CC-BY-NC')],
                        max_length=255,
                    ),
                ),
                ('default_attribution', models.CharField(max_length=255)),
                (
                    'creator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cohort',
            name='contributor',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to='ingest.contributor'
            ),
            preserve_default=False,
        ),
    ]
