# Generated by Django 4.0.3 on 2022-05-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0019_alter_accessionreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='original_blob_name',
            field=models.CharField(db_index=True, editable=False, max_length=255, null=True),
        ),
    ]
