# Generated by Django 4.0.3 on 2022-05-09 13:37
from __future__ import annotations

from django.db import migrations
from django.db.models.expressions import F


def populate_original_blob_name(apps, schema_editor):
    Accession = apps.get_model("ingest", "Accession")
    Accession.objects.filter(original_blob_name__isnull=True).update(
        original_blob_name=F("blob_name")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0020_accession_original_blob_name"),
    ]

    operations = [
        migrations.RunPython(populate_original_blob_name),
    ]
