# Generated by Django 5.1.8 on 2025-05-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0020_remove_accession_valid_legacy_dx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accession",
            name="image_manipulation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
