# Generated by Django 5.1.8 on 2025-05-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0021_accession_image_manipulation"),
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(
                fields=["image_manipulation"], name="ingest_acce_image_m_aee960_idx"
            ),
        ),
    ]
