# Generated by Django 3.1.4 on 2021-03-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0021_auto_20210310_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(help_text='foo', max_length=255),
        ),
    ]
