# Generated by Django 3.1.4 on 2021-03-10 23:07
# flake8: noqa

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0022_auto_20210310_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='description',
            field=models.TextField(
                help_text='The description of your Cohort.<strong>This is private</strong>, and will not be published along with your images.'
            ),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(
                help_text='The name of your Cohort. <strong>This is private</strong>, and will not be published along with your images.',
                max_length=255,
            ),
        ),
    ]
