# Generated by Django 5.1.8 on 2025-05-14 17:14

from django.db import migrations, models
import s3_file_field.fields

import isic.ingest.models.accession


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0022_accession_ingest_acce_image_m_aee960_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="accession",
            name="public_blob",
            field=s3_file_field.fields.S3FileField(
                blank=True,
                storage=isic.ingest.models.accession.public_blob_storage,
                upload_to=isic.ingest.models.accession.public_blob_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="accession",
            name="public_blob_name",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="accession",
            name="public_blob_size",
            field=models.PositiveBigIntegerField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
    ]
