# Generated by Django 5.1.8 on 2025-05-15 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0022_accession_ingest_acce_image_m_aee960_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="metadatafile",
            constraint=models.CheckConstraint(
                condition=models.Q(("blob", ""), _negated=True), name="blob_not_empty"
            ),
        ),
    ]
