# Generated by Django 5.1.8 on 2025-05-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0022_accession_ingest_acce_image_m_aee960_idx"),
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accession",
            name="accession_unique_blob_name",
        ),
        migrations.RemoveConstraint(
            model_name="accession",
            name="accession_blob_name_not_original_blob_name",
        ),
        migrations.RemoveConstraint(
            model_name="accession",
            name="accession_succeeded_blob_fields",
        ),
        migrations.RemoveField(
            model_name="accession",
            name="blob_name",
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("blob_size__isnull", False),
                        ("height__isnull", False),
                        ("status", "succeeded"),
                        ("thumbnail_256_size__isnull", False),
                        ("width__isnull", False),
                        models.Q(("thumbnail_256", ""), _negated=True),
                    ),
                    models.Q(("status", "succeeded"), _negated=True),
                    _connector="OR",
                ),
                name="accession_succeeded_blob_fields",
            ),
        ),
    ]
