# Generated by Django 5.1.8 on 2025-05-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0023_remove_accession_accession_unique_blob_name_and_more"),
        #  migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="metadatafile",
            constraint=models.CheckConstraint(
                condition=models.Q(("blob", ""), _negated=True), name="blob_not_empty"
            ),
        ),
    ]
