# Generated by Django 5.1.8 on 2025-05-15 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0023_accession_public_blob_accession_public_blob_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("public_blob", ""), _negated=True),
                fields=("public_blob",),
                name="accession_unique_public_blob",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("public_blob_name", ""), _negated=True),
                fields=("public_blob_name",),
                name="accession_unique_public_blob_name",
            ),
        ),
    ]
