# Generated by Django 3.1.6 on 2021-03-24 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingest', '0023_auto_20210310_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='blob',
            field=s3_file_field.fields.S3FileField(blank=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='blob_size',
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='original_blob',
            field=s3_file_field.fields.S3FileField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cohort',
            name='attribution',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='creator',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.PROTECT, to='auth.user'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zip',
            name='blob',
            field=s3_file_field.fields.S3FileField(),
        ),
        migrations.AlterField(
            model_name='zip',
            name='blob_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='zip',
            name='blob_size',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zip',
            name='cohort',
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='zips',
                to='ingest.cohort',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zip',
            name='creator',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.PROTECT, to='auth.user'
            ),
            preserve_default=False,
        ),
    ]
