# Generated by Django 5.1.8 on 2025-05-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0024_metadatafile_blob_not_empty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accession",
            name="attribution",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
