# Generated by Django 4.0.3 on 2022-05-22 01:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0024_alter_accession_original_blob_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accession",
            unique_together={("cohort", "original_blob_name")},
        ),
    ]
