# Generated by Django 3.2 on 2021-04-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0024_auto_20210324_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zip',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created'),
                    ('extracting', 'Extracting'),
                    ('extracted', 'Extracted'),
                    ('failed', 'Failed'),
                ],
                default='created',
                max_length=20,
            ),
        ),
    ]
