# Generated by Django 5.1.9 on 2025-05-20 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_remove_collection_new_images_alter_collection_images"),
        ("ingest", "0025_alter_accession_attribution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("public", models.BooleanField(default=False)),
                ("collections", models.ManyToManyField(to="core.collection")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublishRequestAccession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "accession",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="ingest.accession"
                    ),
                ),
                (
                    "publish_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingest.publishrequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="publishrequest",
            name="accessions",
            field=models.ManyToManyField(
                through="ingest.PublishRequestAccession", to="ingest.accession"
            ),
        ),
    ]
