# Generated by Django 5.1.9 on 2025-05-20 22:31

from django.conf import settings
from django.db import migrations, models

import isic.ingest.models.accession


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0026_publishrequest_publishrequestaccession_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accession",
            name="accession_succeeded_blob_fields",
        ),
        migrations.AddField(
            model_name="accession",
            name="sponsored_blob",
            field=models.FileField(
                blank=True,
                storage=isic.ingest.models.accession.sponsored_blob_storage,
                upload_to="images/",
            ),
        ),
        migrations.AddField(
            model_name="accession",
            name="sponsored_thumbnail_256_blob",
            field=models.FileField(
                blank=True,
                storage=isic.ingest.models.accession.sponsored_blob_storage,
                upload_to="thumbnails/",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sponsored_blob", ""), _negated=True),
                fields=("sponsored_blob",),
                name="accession_unique_sponsored_blob",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sponsored_thumbnail_256_blob", ""), _negated=True),
                fields=("sponsored_thumbnail_256_blob",),
                name="accession_unique_sponsored_thumbnail_256_blob",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.CheckConstraint(
                condition=models.Q(("blob", ""), ("sponsored_blob", ""), _connector="OR"),
                name="accession_blob_or_sponsored_blob",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sponsored_blob", ""), _negated=True),
                    ("sponsored_thumbnail_256_blob", ""),
                    _connector="OR",
                ),
                name="accession_sponsored_blob_implies_sponsored_thumbnail_256_blob",
            ),
        ),
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("blob_size__isnull", False),
                        ("height__isnull", False),
                        ("status", "succeeded"),
                        ("thumbnail_256_size__isnull", False),
                        ("width__isnull", False),
                    ),
                    models.Q(("status", "succeeded"), _negated=True),
                    _connector="OR",
                ),
                name="accession_succeeded_blob_fields",
            ),
        ),
    ]
