# Generated by Django 5.1.9 on 2025-06-02 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0027_remove_accession_accession_succeeded_blob_fields_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="accession",
            name="ingest_acce_mel_cla_716507_idx",
        ),
        migrations.RemoveField(
            model_name="accession",
            name="mel_class",
        ),
    ]
