# Generated by Django 4.0.3 on 2022-05-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ingest', '0027_alter_accession_blob_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='original_blob_size',
            field=models.PositiveBigIntegerField(default=None, editable=False, null=True),
        ),
    ]
