# Generated by Django 3.2 on 2021-04-21 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0027_checklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklog',
            name='accession',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='checklogs',
                to='ingest.accession',
            ),
        ),
    ]
