# Generated by Django 3.2 on 2021-04-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0028_alter_checklog_accession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zip',
            name='girder_id',
        ),
        migrations.AddField(
            model_name='accession',
            name='girder_id',
            field=models.CharField(
                blank=True, help_text='The image_id from Girder.', max_length=24
            ),
        ),
    ]
