# Generated by Django 4.0.3 on 2022-05-22 02:12
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0028_accession_original_blob_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accession",
            name="original_blob_size",
            field=models.PositiveBigIntegerField(editable=False),
        ),
    ]
