# Generated by Django 5.1.9 on 2025-06-02 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0028_remove_accession_ingest_acce_mel_cla_716507_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="accession",
            name="ingest_acce_mel_typ_5d54e1_idx",
        ),
        migrations.RemoveField(
            model_name="accession",
            name="mel_type",
        ),
    ]
