# Generated by Django 5.1.9 on 2025-06-02 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0029_remove_accession_ingest_acce_mel_typ_5d54e1_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="accession",
            name="ingest_acce_nevus_t_8c8b30_idx",
        ),
        migrations.RemoveField(
            model_name="accession",
            name="nevus_type",
        ),
    ]
