# Generated by Django 4.0.3 on 2022-06-07 23:22
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0029_alter_accession_original_blob_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="accession",
            name="thumbnail_256_size",
            field=models.PositiveIntegerField(default=None, editable=False, null=True),
        ),
    ]
