# Generated by Django 5.1.9 on 2025-06-02 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0030_remove_accession_ingest_acce_nevus_t_8c8b30_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="accession",
            name="accession_benign_malignant",
        ),
        migrations.RemoveField(
            model_name="accession",
            name="benign_malignant",
        ),
    ]
