# Generated by Django 3.2 on 2021-05-07 21:01

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0030_auto_20210507_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='checklog',
            options={'get_latest_by': 'created', 'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='cohort',
            options={'get_latest_by': 'created', 'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='contributor',
            options={'get_latest_by': 'created', 'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='metadatafile',
            options={'get_latest_by': 'created', 'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='zip',
            options={'get_latest_by': 'created', 'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='accession',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, db_index=True
            ),
        ),
        migrations.AlterField(
            model_name='checklog',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, db_index=True
            ),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, db_index=True
            ),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, db_index=True
            ),
        ),
        migrations.AlterField(
            model_name='metadatafile',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, db_index=True
            ),
        ),
        migrations.AlterField(
            model_name='zip',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, db_index=True
            ),
        ),
    ]
