# Generated by Django 5.1.9 on 2025-06-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0031_remove_accession_accession_benign_malignant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadataversion",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="metadataversion",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
