# Generated by Django 3.2 on 2021-05-10 17:55

import django.core.validators
from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0032_alter_distinctnessmeasure_checksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatafile',
            name='blob',
            field=s3_file_field.fields.S3FileField(
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])
                ]
            ),
        ),
    ]
