# Generated by Django 3.2 on 2021-05-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0033_alter_metadatafile_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='diagnosis_check',
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='duplicate_check',
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='lesion_check',
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='phi_check',
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='quality_check',
            field=models.BooleanField(db_index=True, null=True),
        ),
    ]
