# Generated by Django 5.1.9 on 2025-06-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0033_alter_distinctnessmeasure_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="distinctnessmeasure",
            options={},
        ),
        migrations.RemoveField(
            model_name="distinctnessmeasure",
            name="modified",
        ),
        migrations.AlterField(
            model_name="distinctnessmeasure",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
