# Generated by Django 3.2 on 2021-05-11 15:24

import django.core.validators
from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0033_alter_metadatafile_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zip',
            name='blob',
            field=s3_file_field.fields.S3FileField(
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])
                ]
            ),
        ),
    ]
