# Generated by Django 3.2 on 2021-05-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0034_alter_zip_blob'),
        ('ingest', '0034_auto_20210511_2253'),
    ]

    operations = []
