# Generated by Django 4.1.3 on 2022-12-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ingest', '0034_accession_accession_unique_blob_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='zipupload',
            constraint=models.UniqueConstraint(
                condition=models.Q(('blob', ''), _negated=True),
                fields=('blob',),
                name='zipupload_unique_blob',
            ),
        ),
    ]
