# Generated by Django 5.1.11 on 2025-06-25 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0034_alter_distinctnessmeasure_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distinctnessmeasure",
            name="checksum",
            field=models.CharField(
                default="",
                editable=False,
                max_length=64,
                validators=[django.core.validators.RegexValidator("^[0-9a-f]{64}$")],
            ),
            preserve_default=False,
        ),
    ]
