# Generated by Django 3.2 on 2021-05-14 01:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0035_merge_0034_alter_zip_blob_0034_auto_20210511_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None
            ),
        ),
    ]
