# Generated by Django 5.2.3 on 2026-02-19 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0035_alter_distinctnessmeasure_checksum"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accession",
            name="anatom_site_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accession",
            name="anatom_site_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accession",
            name="anatom_site_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accession",
            name="anatom_site_4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accession",
            name="anatom_site_5",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
