# Generated by Django 5.2.3 on 2026-02-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0036_add_anatom_site_hierarchical_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishrequest",
            name="default_attribution",
            field=models.CharField(default="", max_length=200),
        ),
    ]
