# Generated by Django 3.2 on 2021-05-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0036_accession_tags'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accession',
            constraint=models.UniqueConstraint(
                condition=models.Q(_negated=True, girder_id=''),
                fields=('girder_id',),
                name='accession_unique_girder_id',
            ),
        ),
    ]
