# Generated by Django 4.1.10 on 2023-07-31 22:25

from django.db import migrations


def migrate_default_copyright_license(apps, schema_editor):
    Accession = apps.get_model("ingest", "Accession")

    objs = []
    for accession in (
        Accession.objects.select_related("cohort").filter(copyright_license=None).iterator()
    ):
        accession.copyright_license = accession.cohort.default_copyright_license
        objs.append(accession)
    Accession.objects.bulk_update(objs, ["copyright_license"], batch_size=1_000)


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0037_accession_copyright_license"),
    ]

    operations = [migrations.RunPython(migrate_default_copyright_license)]
