# Generated by Django 4.1.10 on 2023-07-31 22:25

from django.db import connection, migrations


def migrate_default_copyright_license(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            "update ingest_accession set copyright_license = ingest_cohort.default_copyright_license from ingest_cohort where ingest_accession.cohort_id = ingest_cohort.id"  # noqa: E501
        )


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0037_accession_copyright_license"),
    ]

    operations = [migrations.RunPython(migrate_default_copyright_license)]
