# Generated by Django 3.2 on 2021-05-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0037_accession_accession_unique_girder_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={},
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(
                condition=models.Q(_negated=True, girder_id=''),
                fields=('girder_id',),
                name='cohort_unique_girder_id',
            ),
        ),
    ]
