# Generated by Django 4.1.10 on 2023-07-31 22:25
# ruff: noqa: E501
from __future__ import annotations

from django.db import connection, migrations


def migrate_default_copyright_license(apps, schema_editor):
    Accession = apps.get_model("ingest", "Accession")
    Cohort = apps.get_model("ingest", "Cohort")

    with connection.cursor() as cursor:
        cursor.execute(
            f"""
UPDATE {Accession._meta.db_table}
SET {Accession.copyright_license.field.column} = {Cohort._meta.db_table}.{Cohort.default_copyright_license.field.column}
FROM {Cohort._meta.db_table}
WHERE {Accession._meta.db_table}.{Accession.cohort.field.column} = {Cohort._meta.db_table}.{Cohort.id.field.column}
AND {Accession._meta.db_table}.{Accession.copyright_license.field.column} IS NULL
"""
        )


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0037_accession_copyright_license"),
    ]

    operations = [migrations.RunPython(migrate_default_copyright_license)]
