# Generated by Django 5.2.3 on 2026-04-28 16:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0038_alter_accessionreview_creator_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="accession",
            name="accession_anatom_site_general",
        ),
        migrations.RemoveField(
            model_name="accession",
            name="anatom_site_general",
        ),
    ]
