# Generated by Django 4.1.10 on 2023-07-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0038_migrate_copyright_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accession",
            name="copyright_license",
            field=models.CharField(
                choices=[("CC-0", "CC-0"), ("CC-BY", "CC-BY"), ("CC-BY-NC", "CC-BY-NC")],
                max_length=255,
            ),
        ),
    ]
