# Generated by Django 3.2 on 2021-05-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0038_auto_20210514_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='accession',
            name='width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
