# Generated by Django 3.2 on 2021-05-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0039_auto_20210518_1604'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accession',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ('height__isnull', False), ('status', 'succeeded'), ('width__isnull', False)
                    ),
                    models.Q(_negated=True, status='succeeded'),
                    _connector='OR',
                ),
                name='accession_wh_status_check',
            ),
        ),
    ]
