# Generated by Django 5.2.3 on 2026-05-29 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0039_drop_anatom_site_general"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accession",
            name="accession_lesion_id_patient_id_exclusion",
        ),
        migrations.RemoveConstraint(
            model_name="accession",
            name="accession_rcm_case_id_lesion_id_exclusion",
        ),
    ]
