# Generated by Django 3.2 on 2021-05-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0040_accession_accession_wh_status_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklog',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='contributor',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='metadatafile',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='zip',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
    ]
