# Generated by Django 4.1.10 on 2023-08-16 03:47
from __future__ import annotations

import django.core.validators
from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0040_migrate_image_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadatafile",
            name="blob",
            field=s3_file_field.fields.S3FileField(
                unique=True,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["csv"])
                ],
            ),
        ),
    ]
