# Generated by Django 3.2 on 2021-05-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0041_auto_20210519_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='girder_id',
            field=models.CharField(
                blank=True, db_index=True, help_text='The image_id from Girder.', max_length=24
            ),
        ),
    ]
