# Generated by Django 5.2.3 on 2026-06-03 05:14

import django.core.validators
from django.db import migrations, models
import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0041_accession_accession_lesion_id_patient_id_exclusion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="description",
            field=models.TextField(
                help_text=(
                    "The description of your Cohort. "
                    "<strong>This is private</strong>, and will not be published along "
                    "with your images. "
                    'Supports <a href="https://www.markdownguide.org/cheat-sheet/">markdown</a>.'
                )
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="legal_contact_info",
            field=models.TextField(
                help_text=(
                    "The person or institution responsible for legal inquiries about your data. "
                    "<strong>This is private</strong>, "
                    "and will not be published along with your images."
                ),
                verbose_name="Legal Contact Information",
            ),
        ),
        migrations.AlterField(
            model_name="metadatafile",
            name="blob",
            field=s3_file_field.fields.S3FileField(
                unique=True,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["csv"])
                ],
                verbose_name="CSV file",
            ),
        ),
        migrations.AlterField(
            model_name="zipupload",
            name="blob",
            field=s3_file_field.fields.S3FileField(
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["zip"])
                ],
                verbose_name="zip file",
            ),
        ),
    ]
