# Generated by Django 4.1.10 on 2023-08-25 21:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import isic.ingest.models.lesion


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0041_alter_metadatafile_blob"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesion",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=isic.ingest.models.lesion._default_id,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator("^IL_[0-9]{7}$")],
                    ),
                ),
                ("private_lesion_id", models.CharField(max_length=255)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesions",
                        to="ingest.cohort",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accession",
            name="lesion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accessions",
                to="ingest.lesion",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesion",
            constraint=models.UniqueConstraint(
                fields=("private_lesion_id", "cohort"), name="unique_lesion"
            ),
        ),
        migrations.AddConstraint(
            model_name="lesion",
            constraint=models.CheckConstraint(
                check=models.Q(("id__regex", "^IL_[0-9]{7}$")), name="lesion_id_valid_format"
            ),
        ),
    ]
