# Generated by Django 3.2 on 2021-05-25 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0042_alter_accession_girder_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accession',
            name='tags',
        ),
    ]
