# Generated by Django 3.2 on 2021-05-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0043_remove_accession_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accession',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='cohort',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
    ]
