# Generated by Django 4.1.10 on 2023-08-29 14:56
from __future__ import annotations

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import isic.ingest.models.patient


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0045_metadataversion_lesion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=isic.ingest.models.patient._default_id,  # noqa: SLF001
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator("^IP_[0-9]{7}$")],
                    ),
                ),
                ("private_patient_id", models.CharField(max_length=255)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="ingest.cohort",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accession",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accessions",
                to="ingest.patient",
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                fields=("private_patient_id", "cohort"), name="unique_patient"
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.CheckConstraint(
                check=models.Q(("id__regex", "^IP_[0-9]{7}$")),
                name="patient_id_valid_format",
            ),
        ),
    ]
