# Generated by Django 3.2 on 2021-05-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0045_contributor_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='Clinical Metadata'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='unstructured_metadata',
            field=models.JSONField(default=dict, verbose_name='Unstructured Metadata'),
        ),
    ]
