# Generated by Django 3.2.6 on 2021-08-19 03:35

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0045_contributor_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='thumbnail_256',
            field=s3_file_field.fields.S3FileField(blank=True),
        ),
    ]
