# Generated by Django 4.1.10 on 2023-08-29 15:18
from __future__ import annotations

import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0045_patient_accession_patient_patient_unique_patient_and_more"),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name="accession",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("lesion_id__isnull", False), ("patient_id__isnull", False)),
                expressions=[("lesion_id", "="), ("patient_id", "<>")],
                name="accession_lesion_id_patient_id_exclusion",
            ),
        ),
    ]
