# Generated by Django 3.2.8 on 2021-10-29 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0046_accession_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='upload',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='accessions',
                to='ingest.zip',
            ),
        ),
    ]
