# Generated by Django 3.2.8 on 2021-10-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0047_alter_accession_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='cohort',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='accessions',
                to='ingest.cohort',
            ),
        ),
    ]
