# Generated by Django 4.1.13 on 2024-02-13 16:56
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
from django.db.models.expressions import OuterRef, Subquery


def set_copyright_license(apps, schema_editor):
    Accession = apps.get_model("ingest", "Accession")

    Accession.objects.filter(copyright_license="").update(
        copyright_license=Subquery(
            Accession.objects.filter(id=OuterRef("id"))
            .annotate(default_copyright_license=models.F("cohort__default_copyright_license"))
            .values("default_copyright_license")[:1]
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0048_metadatafile_validation_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accession",
            name="blob_size",
            field=models.PositiveBigIntegerField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="accession",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accession",
            name="lesion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accessions",
                to="ingest.lesion",
            ),
        ),
        migrations.AlterField(
            model_name="accession",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="accession",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accessions",
                to="ingest.patient",
            ),
        ),
        migrations.AlterField(
            model_name="accession",
            name="thumbnail_256_size",
            field=models.PositiveIntegerField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="accession",
            name="unstructured_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="accession",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accession",
            name="zip_upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accessions",
                to="ingest.zipupload",
            ),
        ),
        migrations.RunPython(set_copyright_license),
    ]
