# Generated by Django 3.2.8 on 2021-10-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0049_auto_20211029_1638'),
    ]

    # https://code.djangoproject.com/ticket/25253#comment:15
    operations = [
        migrations.RunSQL(
            """
            alter table ingest_accession alter column cohort_id set not null;
            """,
            state_operations=[
                migrations.AlterField(
                    model_name='accession',
                    name='cohort',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='accessions',
                        to='ingest.cohort',
                    ),
                )
            ],
        )
    ]
