# Generated by Django 3.2.8 on 2021-10-29 21:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingest', '0050_alter_accession_cohort'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zip',
            new_name='ZipUpload',
        ),
    ]
