# Generated by Django 4.1.13 on 2024-02-26 15:28
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0050_accession_primary_biopsy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accession",
            old_name="primary_biopsy",
            new_name="concomitant_biopsy",
        ),
    ]
