# Generated by Django 3.2.8 on 2021-10-29 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0051_rename_zip_zipupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipupload',
            name='cohort',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='zip_uploads',
                to='ingest.cohort',
            ),
        ),
    ]
