# Generated by Django 3.2.8 on 2021-10-31 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0052_alter_zipupload_cohort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accession',
            old_name='upload',
            new_name='zip_upload',
        ),
        migrations.AlterUniqueTogether(
            name='accession',
            unique_together={('zip_upload', 'blob_name')},
        ),
    ]
