# Generated by Django 4.1.13 on 2024-03-05 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0052_accession_accession_concomitant_biopsy_diagnosis_confirm_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnstructuredMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.JSONField(blank=True, default=dict)),
                (
                    "accession",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unstructured_metadata_tmp",
                        to="ingest.accession",
                    ),
                ),
            ],
        ),
    ]
