# Generated by Django 3.2.8 on 2021-11-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0053_auto_20211031_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='attribution',
            field=models.CharField(
                help_text='The institution name that should be attributed.', max_length=200
            ),
        ),
    ]
