# Generated by Django 4.1.13 on 2024-02-29 03:17
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0053_accession_acquisition_day_accession_age_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accession",
            name="accession_concomitant_biopsy_diagnosis_confirm_type",
        ),
    ]
