# Generated by Django 4.1.13 on 2024-03-05 21:48
from __future__ import annotations

from django.db import migrations
from more_itertools import ichunked


def populate_unstructured_metadata_relationship(apps, schema_editor):
    Accession = apps.get_model("ingest", "Accession")
    UnstructuredMetadata = apps.get_model("ingest", "UnstructuredMetadata")

    for accessions in ichunked(Accession.objects.iterator(), 5_000):
        batch = [
            UnstructuredMetadata(accession=accession, value=accession.unstructured_metadata)
            for accession in accessions
        ]
        UnstructuredMetadata.objects.bulk_create(batch)


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0053_unstructuredmetadata"),
    ]

    operations = [
        migrations.RunPython(populate_unstructured_metadata_relationship),
    ]
