# Generated by Django 3.2.11 on 2022-01-13 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingest', '0054_alter_cohort_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='creator',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='accessions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunSQL(
            """
            UPDATE ingest_accession set creator_id = ingest_zipupload.creator_id
            FROM ingest_zipupload, ingest_cohort
            WHERE ingest_accession.zip_upload_id = ingest_zipupload.id
            AND ingest_accession.creator_id is null;
            """
        ),
        migrations.RunSQL(
            """
            UPDATE ingest_accession set creator_id = ingest_cohort.creator_id
            FROM ingest_cohort
            WHERE ingest_accession.cohort_id = ingest_cohort.id
            AND ingest_accession.creator_id is null AND ingest_accession.zip_upload_id is null;
            """
        ),
    ]
