# Generated by Django 4.1.13 on 2024-03-05 21:54
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0054_populate_unstructured_metadata_relationship"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accession",
            name="unstructured_metadata",
        ),
        migrations.AlterField(
            model_name="unstructuredmetadata",
            name="accession",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unstructured_metadata",
                to="ingest.accession",
            ),
        ),
    ]
