# Generated by Django 4.1.13 on 2024-02-29 03:20
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0054_remove_accession_accession_concomitant_biopsy_diagnosis_confirm_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("concomitant_biopsy", True), ("diagnosis_confirm_type", "histopathology")
                    ),
                    models.Q(("concomitant_biopsy", True), _negated=True),
                    _connector="OR",
                ),
                name="accession_concomitant_biopsy_diagnosis_confirm_type",
            ),
        ),
    ]
