# Generated by Django 3.2.11 on 2022-01-13 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingest', '0055_accession_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='creator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='accessions',
                to='auth.user',
            ),
        ),
    ]
