# Generated by Django 3.2.11 on 2022-01-14 15:50
import os

from django.db import migrations
from django.db.models import Count


def remove_duplicate_blob_names(apps, schema_editor):
    Cohort = apps.get_model('ingest', 'Cohort')  # noqa: N806

    for cohort in Cohort.objects.all():
        for dupe_blob_name in (
            cohort.accessions.values_list('blob_name', flat=True)
            .alias(c=Count('pk', distinct=True))
            .filter(c__gt=1)
            .order_by()
        ):
            dupe_accessions = cohort.accessions.filter(blob_name=dupe_blob_name)
            for i, accession in enumerate(dupe_accessions):
                name, ext = os.path.splitext(accession.blob_name)
                accession.blob_name = f'{name}-{i}{ext}'
                accession.save(update_fields=['blob_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0056_alter_accession_creator'),
    ]

    operations = [migrations.RunPython(remove_duplicate_blob_names)]
