# Generated by Django 4.1.13 on 2024-02-29 20:28
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0056_rename_metadata_accession_metadata_old"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accession",
            name="concomitant_biopsy",
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
