# Generated by Django 4.1.13 on 2024-03-09 04:28
from __future__ import annotations

from django.db import migrations


def migrate_metadata(apps, schema_editor):
    Accession = apps.get_model("ingest", "Accession")

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"""
            UPDATE {Accession._meta.db_table}
            SET
                concomitant_biopsy = (metadata_old->>'concomitant_biopsy')::bool,
                fitzpatrick_skin_type = metadata_old->>'fitzpatrick_skin_type',
                age = (metadata_old->>'age')::int,
                sex = metadata_old->>'sex',
                anatom_site_general = metadata_old->>'anatom_site_general',
                benign_malignant = metadata_old->>'benign_malignant',
                diagnosis = metadata_old->>'diagnosis',
                diagnosis_confirm_type = metadata_old->>'diagnosis_confirm_type',
                personal_hx_mm = (metadata_old->>'personal_hx_mm')::bool,
                family_hx_mm = (metadata_old->>'family_hx_mm')::bool,
                clin_size_long_diam_mm = (metadata_old->>'clin_size_long_diam_mm')::numeric,
                melanocytic = (metadata_old->>'melanocytic')::bool,
                mel_class = metadata_old->>'mel_class',
                mel_mitotic_index = metadata_old->>'mel_mitotic_index',
                mel_thick_mm = (metadata_old->>'mel_thick_mm')::numeric,
                mel_type = metadata_old->>'mel_type',
                mel_ulcer = (metadata_old->>'mel_ulcer')::bool,
                acquisition_day = (metadata_old->>'acquisition_day')::int,
                nevus_type = metadata_old->>'nevus_type',
                image_type = metadata_old->>'image_type',
                dermoscopic_type = metadata_old->>'dermoscopic_type',
                tbp_tile_type = metadata_old->>'tbp_tile_type'
                """
        )


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0057_alter_accession_concomitant_biopsy"),
    ]

    operations = [
        migrations.RunPython(migrate_metadata),
    ]
