# Generated by Django 3.2.11 on 2022-01-27 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0057_auto_20220114_1550'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accession',
            unique_together={('cohort', 'blob_name')},
        ),
    ]
