# Generated by Django 4.1.13 on 2024-03-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0059_remove_accession_metadata_old"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accession",
            name="blob_name",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
