# Generated by Django 4.1.13 on 2024-03-11 18:51
from __future__ import annotations

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0060_alter_accession_blob_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="distinctnessmeasure",
            options={},
        ),
        migrations.AlterField(
            model_name="accession",
            name="concomitant_biopsy",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accession",
            name="girder_id",
            field=models.CharField(
                blank=True, help_text="The image_id from Girder.", max_length=24
            ),
        ),
        migrations.AlterField(
            model_name="accession",
            name="original_blob_name",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="distinctnessmeasure",
            name="checksum",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                null=True,
                validators=[django.core.validators.RegexValidator("^[0-9a-f]{64}$")],
            ),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(
                fields=["original_blob_name"], name="ingest_acce_origina_23620f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accession",
            index=models.Index(fields=["girder_id"], name="ingest_acce_girder__d68973_idx"),
        ),
        migrations.AddIndex(
            model_name="distinctnessmeasure",
            index=models.Index(fields=["checksum"], name="ingest_dist_checksu_cde183_idx"),
        ),
    ]
