# Generated by Django 4.1.13 on 2024-03-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0061_alter_distinctnessmeasure_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unstructuredmetadata",
            name="accession",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unstructured_metadata",
                to="ingest.accession",
            ),
        ),
    ]
