# Generated by Django 4.1.13 on 2024-03-13 15:37
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0062_alter_unstructuredmetadata_accession"),
    ]

    operations = [
        migrations.AddField(
            model_name="zipupload",
            name="fail_reason",
            field=models.CharField(
                blank=True,
                choices=[("duplicates", "Duplicates"), ("invalid", "Invalid"), ("other", "Other")],
                max_length=10,
            ),
        ),
    ]
