# Generated by Django 4.1.13 on 2024-03-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0063_zipupload_fail_reason"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="zipupload",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "failed"), models.Q(("fail_reason", ""), _negated=True)),
                    models.Q(("status", "failed"), _negated=True),
                    _connector="OR",
                ),
                name="zipupload_fail_reason_requires_failed_status",
            ),
        ),
    ]
