# Generated by Django 5.0.4 on 2024-05-14 17:08

from django.db import migrations, models
import django.db.models.deletion

import isic.ingest.models.rcm_case


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0064_zipupload_zipupload_fail_reason_requires_failed_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadataversion",
            name="rcm_case",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="RcmCase",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=isic.ingest.models.rcm_case._default_id,  # noqa: SLF001
                        max_length=7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("private_rcm_case_id", models.CharField(max_length=255)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rcm_cases",
                        to="ingest.cohort",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accession",
            name="rcm_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accessions",
                to="ingest.rcmcase",
            ),
        ),
        migrations.AddConstraint(
            model_name="rcmcase",
            constraint=models.UniqueConstraint(
                fields=("private_rcm_case_id", "cohort"), name="unique_rcm_case"
            ),
        ),
    ]
