# Generated by Django 5.0.4 on 2024-05-15 20:34

from django.conf import settings
import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0065_metadataversion_rcm_case_rcmcase_accession_rcm_case_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="accession",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("rcm_case_id__isnull", False), ("lesion_id__isnull", False)),
                expressions=[("rcm_case_id", "="), ("lesion_id", "<>")],
                name="accession_rcm_case_id_lesion_id_exclusion",
            ),
        ),
    ]
