# Generated by Django 4.2.13 on 2024-05-16 16:04

from django.db import migrations, models
import isic_metadata.fields


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0066_accession_accession_rcm_case_id_lesion_id_exclusion"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="accession",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "image_type",
                        isic_metadata.fields.ImageTypeEnum["rcm_macroscopic"],
                    )
                ),
                fields=("cohort_id", "rcm_case_id"),
                name="accession_unique_rcm_case_id_macroscopic_image",
            ),
        ),
    ]
