# Generated by Django 5.2.16 on 2026-09-14 12:11

from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import oauth2_provider.generators
from pgvector.django import VectorExtension
import s3_file_field.fields

import isic.core.models.doi
import isic.core.models.supplemental_file


class Migration(migrations.Migration):
    replaces = [
        ("core", "0001_initial"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        VectorExtension(),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text='Supports <a href="https://www.markdownguide.org/cheat-sheet/">markdown</a>.',
                    ),
                ),
                ("public", models.BooleanField(default=False)),
                ("pinned", models.BooleanField(default=False)),
                ("locked", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GirderDataset",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator("^[0-9a-f]{24}$")],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("public", models.BooleanField()),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="GirderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("non_image", "Non-Image"),
                            ("corrupt", "Corrupt"),
                            ("migrated", "Migrated"),
                            ("true_duplicate", "True Duplicate"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("pre_review", models.BooleanField(null=True)),
                (
                    "item_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=24,
                        unique=True,
                        validators=[django.core.validators.RegexValidator("^[0-9a-f]{24}$")],
                    ),
                ),
                (
                    "file_id",
                    models.CharField(
                        editable=False,
                        max_length=24,
                        unique=True,
                        validators=[django.core.validators.RegexValidator("^[0-9a-f]{24}$")],
                    ),
                ),
                ("original_filename", models.CharField(editable=False, max_length=255)),
                (
                    "original_file_relpath",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                (
                    "unstructured_metadata",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                (
                    "original_blob_dm",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        validators=[django.core.validators.RegexValidator("^[0-9a-f]{64}$")],
                    ),
                ),
                (
                    "stripped_blob_dm",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        validators=[django.core.validators.RegexValidator("^[0-9a-f]{64}$")],
                    ),
                ),
                ("raw", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["item_id"],
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, db_index=True
                    ),
                ),
                ("public", models.BooleanField(db_index=True, default=False)),
                ("pinned", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["created"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImageAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Image aliases",
            },
        ),
        migrations.CreateModel(
            name="ImageShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IsicId",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator("^ISIC_[0-9]{7}$")],
                        verbose_name="ISIC ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IsicOAuthApplication",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.CharField(
                        db_index=True,
                        default=oauth2_provider.generators.generate_client_id,
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "redirect_uris",
                    models.TextField(blank=True, help_text="Allowed URIs list, space separated"),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("confidential", "Confidential"),
                            ("public", "Public"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "authorization_grant_type",
                    models.CharField(
                        choices=[
                            ("authorization-code", "Authorization code"),
                            ("implicit", "Implicit"),
                            ("password", "Resource owner password-based"),
                            ("client-credentials", "Client credentials"),
                            ("openid-hybrid", "OpenID connect hybrid"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "client_secret",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=oauth2_provider.generators.generate_client_secret,
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("skip_authorization", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "algorithm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No OIDC support"),
                            ("RS256", "RSA with SHA-2 256"),
                            ("HS256", "HMAC with SHA-2 256"),
                        ],
                        default="",
                        max_length=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "ISIC OAuth application",
            },
        ),
        migrations.CreateModel(
            name="Segmentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "girder_id",
                    models.CharField(
                        max_length=24,
                        unique=True,
                        validators=[django.core.validators.RegexValidator("^[0-9a-f]{24}$")],
                    ),
                ),
                ("mask", s3_file_field.fields.S3FileField(blank=True)),
                ("meta", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SegmentationReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("approved", models.BooleanField()),
                (
                    "skill",
                    models.CharField(
                        choices=[("novice", "novice"), ("expert", "expert")],
                        max_length=6,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplementalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("filename", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "blob",
                    models.FileField(
                        storage=isic.core.models.supplemental_file.supplemental_file_storage,
                        upload_to=isic.core.models.supplemental_file.supplemental_file_upload_to,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CollectionCount",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="cached_counts",
                        serialize=False,
                        to="core.collection",
                    ),
                ),
                ("lesion_count", models.PositiveIntegerField()),
                ("patient_count", models.PositiveIntegerField()),
                ("image_count", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "materialized_collection_counts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CollectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_images",
                        to="core.collection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_shares",
                        to="core.collection",
                    ),
                ),
                (
                    "grantee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_shares_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grantor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collection_shares_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="shares",
            field=models.ManyToManyField(
                related_name="collection_shares",
                through="core.CollectionShare",
                through_fields=("collection", "grantee"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Doi",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=isic.core.models.doi._generate_random_doi_id,  # noqa: SLF001
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator("^\\d+\\.\\d+/\\d+$")],
                    ),
                ),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("bundle_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("metadata_size", models.PositiveIntegerField(blank=True, null=True)),
                ("citations", models.JSONField(blank=True, default=dict)),
                ("schema_org_dataset", models.JSONField(blank=True, default=dict)),
                (
                    "bundle",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=isic.core.models.doi.doi_storage,
                        upload_to=isic.core.models.doi.doi_upload_to,
                    ),
                ),
                (
                    "metadata",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=isic.core.models.doi.doi_storage,
                        upload_to=isic.core.models.doi.doi_upload_to,
                    ),
                ),
                (
                    "collection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DOI",
                "verbose_name_plural": "DOIs",
            },
        ),
        migrations.CreateModel(
            name="DoiRelatedIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("IsReferencedBy", "Is Referenced By"),
                            ("IsSupplementedBy", "Is Supplemented By"),
                            ("IsDescribedBy", "Is Described By"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "related_identifier_type",
                    models.CharField(choices=[("DOI", "DOI"), ("URL", "URL")], max_length=10),
                ),
                ("related_identifier", models.CharField(max_length=500)),
                (
                    "doi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_identifiers",
                        to="core.doi",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DraftDoi",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=isic.core.models.doi._generate_random_doi_id,  # noqa: SLF001
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator("^\\d+\\.\\d+/\\d+$")],
                    ),
                ),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("bundle", models.FileField(blank=True, null=True, upload_to="")),
                ("bundle_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("metadata", models.FileField(blank=True, null=True, upload_to="")),
                ("metadata_size", models.PositiveIntegerField(blank=True, null=True)),
                ("citations", models.JSONField(blank=True, default=dict)),
                ("schema_org_dataset", models.JSONField(blank=True, default=dict)),
                ("is_publishing", models.BooleanField(default=False)),
                (
                    "collection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Draft DOI",
                "verbose_name_plural": "Draft DOIs",
            },
        ),
        migrations.CreateModel(
            name="DraftDoiRelatedIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("IsReferencedBy", "Is Referenced By"),
                            ("IsSupplementedBy", "Is Supplemented By"),
                            ("IsDescribedBy", "Is Described By"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "related_identifier_type",
                    models.CharField(choices=[("DOI", "DOI"), ("URL", "URL")], max_length=10),
                ),
                ("related_identifier", models.CharField(max_length=500)),
                (
                    "doi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_identifiers",
                        to="core.draftdoi",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DraftSupplementalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("filename", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("blob", s3_file_field.fields.S3FileField()),
                (
                    "doi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplemental_files",
                        to="core.draftdoi",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
    ]
