# Generated by Django 5.2.16 on 2026-09-14 12:11

from __future__ import annotations

from typing import TYPE_CHECKING

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import pgvector.django.halfvec
import pgvector.django.indexes

from isic.core.search import IMAGE_INDEX_MAPPINGS, LESION_INDEX_MAPPINGS, maybe_create_index

if TYPE_CHECKING:
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.state import StateApps


def update_default_site(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Site = apps.get_model("sites", "Site")

    # A default site object may or may not exist.
    # If this is a brand-new database, the post_migrate will not fire until the very end of the
    # "migrate" command, so the sites app will not have created a default site object yet.
    # If this is an existing database, the sites app will likely have created an default site
    # object already.
    Site.objects.update_or_create(
        pk=settings.SITE_ID,
        defaults={
            "domain": "api.isic-archive.com",
            "name": "ISIC Archive",
        },
    )


def rollback_default_site(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Site = apps.get_model("sites", "Site")

    # This is the initial value of the default site object, as populated by the sites app.
    # If it doesn't exist for some reason, there is nothing to roll back.
    Site.objects.filter(pk=settings.SITE_ID).update(domain="example.com", name="example.com")


def setup_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("auth", "User")

    for group_name in ["Public", "ISIC Staff"]:
        Group.objects.get_or_create(name=group_name)

    public = Group.objects.get(name="Public")
    public.user_set.set(User.objects.all())


def create_elasticsearch_index(apps, schema_editor):
    maybe_create_index(settings.ISIC_ELASTICSEARCH_IMAGES_INDEX, IMAGE_INDEX_MAPPINGS)
    maybe_create_index(settings.ISIC_ELASTICSEARCH_LESIONS_INDEX, LESION_INDEX_MAPPINGS)


class Migration(migrations.Migration):
    replaces = [
        ("core", "0002_initial"),
        ("core", "0003_auto_20240701_1459"),
        ("core", "0004_alter_collection_description_squashed_0023_alter_image_options"),
        ("core", "0024_collection_collection_pinned_implies_public"),
        ("core", "0025_alter_collection_shares_alter_image_shares"),
        ("core", "0026_invert_doi_fk"),
        ("core", "0027_doirelatedidentifier"),
        ("core", "0028_alter_doirelatedidentifier_options_and_more"),
        ("core", "0029_add_doi_is_draft"),
        ("core", "0030_draftdoi_draftdoirelatedidentifier_and_more"),
        ("core", "0031_fix_materialized_view_empty_collections"),
        ("core", "0031_alter_draftdoi_bundle_alter_draftdoi_metadata"),
        ("core", "0032_add_is_publishing_to_draftdoi"),
        ("core", "0033_pgvector"),
        ("core", "0034_image_embedding_image_image_embedding_public_check"),
        ("core", "0035_image_image_embedding_ivfflat_idx"),
        ("core", "0036_add_image_embedding_table"),
        ("core", "0037_remove_image_embedding_field"),
        ("core", "0038_change_embedding_index_to_cosine"),
        ("core", "0001_default_site"),
        ("core", "0039_merge"),
        ("core", "0040_alter_supplementalfile_blob"),
        ("core", "0041_alter_collection_creator_and_more"),
        ("core", "0042_pinned_images"),
        ("core", "0043_image_image_pinned_implies_public"),
        ("core", "0044_image_pin_nonnull"),
    ]

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_squashed_0044_image_pin_nonnull"),
        ("ingest", "0001_squashed_0043_alter_rcmcase_id"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="girderimage",
            name="accession",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ingest.accession",
            ),
        ),
        migrations.AddField(
            model_name="girderimage",
            name="dataset",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="images",
                to="core.girderdataset",
            ),
        ),
        migrations.CreateModel(
            name="ImageEmbedding",
            fields=[
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="embedding_relation",
                        serialize=False,
                        to="core.image",
                    ),
                ),
                ("embedding", pgvector.django.halfvec.HalfVectorField(dimensions=3584)),
            ],
        ),
        migrations.AddField(
            model_name="image",
            name="accession",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="ingest.accession"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="published_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collectionimage",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_images",
                to="core.image",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="images",
            field=models.ManyToManyField(
                related_name="collections",
                through="core.CollectionImage",
                to="core.image",
            ),
        ),
        migrations.AddField(
            model_name="imagealias",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aliases",
                to="core.image",
            ),
        ),
        migrations.AddField(
            model_name="imageshare",
            name="grantee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_shares_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="imageshare",
            name="grantor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shares",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="imageshare",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_shares",
                to="core.image",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="shares",
            field=models.ManyToManyField(
                through="core.ImageShare",
                through_fields=("image", "grantee"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="imagealias",
            name="isic",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.isicid",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="isic",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.isicid",
                verbose_name="isic id",
            ),
        ),
        migrations.AddField(
            model_name="girderimage",
            name="isic",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.isicid",
            ),
        ),
        migrations.AddField(
            model_name="isicoauthapplication",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="segmentation",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="segmentations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="segmentation",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="segmentations",
                to="core.image",
            ),
        ),
        migrations.AddField(
            model_name="segmentationreview",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="segmentation_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="segmentationreview",
            name="segmentation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="core.segmentation",
            ),
        ),
        migrations.AddField(
            model_name="supplementalfile",
            name="doi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplemental_files",
                to="core.doi",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionshare",
            constraint=models.CheckConstraint(
                condition=models.Q(("grantor", models.F("grantee")), _negated=True),
                name="collectionshare_grantor_grantee_diff_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionshare",
            constraint=models.UniqueConstraint(
                fields=("grantor", "collection", "grantee"),
                name="collectionshare_grantor_collection_grantee_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="doirelatedidentifier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("relation_type", "IsDescribedBy")),
                fields=("doi",),
                name="doirelatedidentifier_unique_isdescribedby_per_doi",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="doirelatedidentifier",
            unique_together={
                (
                    "doi",
                    "relation_type",
                    "related_identifier_type",
                    "related_identifier",
                )
            },
        ),
        migrations.AddConstraint(
            model_name="draftdoirelatedidentifier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("relation_type", "IsDescribedBy")),
                fields=("doi",),
                name="draftdoirelatedidentifier_unique_isdescribedby_per_doi",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="draftdoirelatedidentifier",
            unique_together={
                (
                    "doi",
                    "relation_type",
                    "related_identifier_type",
                    "related_identifier",
                )
            },
        ),
        migrations.AddIndex(
            model_name="imageembedding",
            index=pgvector.django.indexes.IvfflatIndex(
                fields=["embedding"],
                lists=1000,
                name="imageembedding_embed_ivfflat",
                opclasses=["halfvec_cosine_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionimage",
            constraint=models.UniqueConstraint(
                fields=("collection", "image"),
                name="collectionimage_collection_image_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("name"), name="gin_trgm_ops"
                ),
                name="collection_name_gin",
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pinned", True)),
                fields=("name",),
                name="collection_pinned_has_unique_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.CheckConstraint(
                condition=models.Q(("pinned", False), ("public", True), _connector="OR"),
                name="collection_pinned_implies_public",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collection",
            unique_together={("creator", "name")},
        ),
        migrations.AddConstraint(
            model_name="imageshare",
            constraint=models.CheckConstraint(
                condition=models.Q(("grantor", models.F("grantee")), _negated=True),
                name="imageshare_grantor_grantee_diff_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="imageshare",
            constraint=models.UniqueConstraint(
                fields=("grantor", "image", "grantee"),
                name="imageshare_grantor_image_grantee_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("isic"), name="gin_trgm_ops"
                ),
                name="isic_name_gin",
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(fields=["-pinned", "created"], name="pinned_created_index"),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.CheckConstraint(
                condition=models.Q(("pinned", 0), ("public", True), _connector="OR"),
                name="image_pinned_implies_public",
            ),
        ),
        migrations.AddConstraint(
            model_name="girderimage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "unknown"),
                    ("status", "non_image"),
                    ("accession__isnull", False),
                    _connector="OR",
                ),
                name="non_unknown_have_accession",
            ),
        ),
        migrations.AddConstraint(
            model_name="girderimage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "non_image"),
                    models.Q(("stripped_blob_dm", ""), _negated=True),
                    _connector="OR",
                ),
                name="non_non_image_have_stripped_blob_dm",
            ),
        ),
        migrations.AddConstraint(
            model_name="segmentation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("mask", ""), _negated=True),
                fields=("mask",),
                name="segmentation_unique_mask",
            ),
        ),
        migrations.RunPython(update_default_site, rollback_default_site, elidable=False),
        migrations.RunPython(setup_groups, elidable=False),
        migrations.RunPython(create_elasticsearch_index, elidable=False),
        migrations.RunSQL(
            sql="""
DROP MATERIALIZED VIEW IF EXISTS materialized_collection_counts;

CREATE MATERIALIZED VIEW materialized_collection_counts AS
SELECT
    c.id AS id,
    COUNT(DISTINCT ingest_accession.lesion_id) AS lesion_count,
    COUNT(DISTINCT ingest_accession.patient_id) AS patient_count,
    COUNT(ci.image_id) AS image_count
FROM core_collection AS c
LEFT JOIN core_collectionimage AS ci ON c.id = ci.collection_id
LEFT JOIN core_image ON ci.image_id = core_image.id
LEFT JOIN ingest_accession ON core_image.accession_id = ingest_accession.id
GROUP BY c.id;

-- a unique index is necessary to be able to refresh the materialized view concurrently
CREATE UNIQUE INDEX IF NOT EXISTS materialized_collection_counts_unique_id
ON materialized_collection_counts (id);
            """,
            elidable=False,
        ),
    ]
