# Generated by Django 3.2 on 2021-04-28 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial_squashed'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicateimage',
            name='accession',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='duplicates',
                to='ingest.accession',
            ),
        ),
    ]
