# Generated by Django 4.2.13 on 2024-07-01 14:59

from django.conf import settings
from django.db import migrations

from isic.core.search import IMAGE_INDEX_MAPPINGS, LESION_INDEX_MAPPINGS, maybe_create_index


def create_elasticsearch_index(apps, schema_editor):
    maybe_create_index(settings.ISIC_ELASTICSEARCH_IMAGES_INDEX, IMAGE_INDEX_MAPPINGS)
    maybe_create_index(settings.ISIC_ELASTICSEARCH_LESIONS_INDEX, LESION_INDEX_MAPPINGS)


def setup_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("auth", "User")

    for group_name in ["Public", "ISIC Staff"]:
        Group.objects.get_or_create(name=group_name)

    public = Group.objects.get(name="Public")
    public.user_set.set(User.objects.all())


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        ("sites", "0002_alter_domain_unique"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(setup_groups, elidable=False),
        migrations.RunPython(create_elasticsearch_index, elidable=False),
    ]
