# Generated by Django 5.1.3 on 2024-11-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_auto_20240701_1459"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=models.TextField(
                blank=True,
                help_text='Supports <a href="https://www.markdownguide.org/cheat-sheet/">markdown</a>.',
            ),
        ),
    ]
