# Generated by Django 5.1.5 on 2025-02-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_collection_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="doi",
            name="bundle",
            field=models.FileField(blank=True, null=True, upload_to="doi-bundles/"),
        ),
    ]
