# Generated by Django 3.2 on 2021-05-24 23:50

from functools import lru_cache

from django.db import migrations


def populate_collections(apps, schema_editor):
    Image = apps.get_model('core', 'Image')  # noqa
    Collection = apps.get_model('core', 'Collection')  # noqa

    @lru_cache
    def get_or_create_coll(name):
        coll, _ = Collection.objects.get_or_create(name=name)
        return coll

    images = Image.objects.select_related('accession').all()
    for image in images:
        for tag in image.accession.tags:
            get_or_create_coll(tag).images.add(image)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_collection'),
    ]

    operations = [migrations.RunPython(populate_collections)]
