# Generated by Django 3.2 on 2021-05-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='images',
            field=models.ManyToManyField(related_name='collections', to='core.Image'),
        ),
    ]
