# Generated by Django 5.1.5 on 2025-02-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_doi_bundle"),
    ]

    operations = [
        migrations.AddField(
            model_name="doi",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
