# Generated by Django 5.1.5 on 2025-02-18 15:09

from django.db import migrations, models
from django.utils.text import slugify


def populate_doi_slugs(apps, schema_editor):
    Doi = apps.get_model("core", "Doi")
    for doi in Doi.objects.all():
        doi.slug = slugify(doi.collection.name)
        doi.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_doi_slug"),
    ]

    operations = [
        migrations.RunPython(
            populate_doi_slugs,
            elidable=True,
        ),
        migrations.AlterField(
            model_name="doi",
            name="slug",
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
