# Generated by Django 3.2 on 2021-05-26 02:32

from django.db import migrations, models
import django.db.models.deletion

import isic.core.models.isic_id


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_isic_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duplicateimage",
            name="isic",
            field=models.OneToOneField(
                editable=False, on_delete=django.db.models.deletion.PROTECT, to="core.isicid"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="isic",
            field=models.OneToOneField(
                default=isic.core.models.isic_id.IsicId.safe_create,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.isicid",
            ),
        ),
        migrations.AlterField(
            model_name="imageredirect",
            name="isic",
            field=models.OneToOneField(
                editable=False, on_delete=django.db.models.deletion.PROTECT, to="core.isicid"
            ),
        ),
    ]
