# Generated by Django 5.1.5 on 2025-02-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_doi_bundle_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="doi",
            name="citations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
