# Generated by Django 3.2.3 on 2021-06-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_auto_20210602_1658"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="girderimage",
            name="girder_id_notnull",
        ),
        migrations.AddConstraint(
            model_name="girderimage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("status", "unknown"), ("accession_id__isnull", False), _connector="OR"
                ),
                name="non_unknown_have_accession_id",
            ),
        ),
    ]
