# Generated by Django 5.1.5 on 2025-02-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_doi_citations"),
    ]

    operations = [
        migrations.AddField(
            model_name="doi",
            name="metadata",
            field=models.FileField(blank=True, null=True, upload_to="doi-bundles/"),
        ),
        migrations.AddField(
            model_name="doi",
            name="metadata_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
