# Generated by Django 3.2.3 on 2021-06-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_alter_girderimage_accession_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girderimage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='girderimage',
            name='unstructured_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
