# Generated by Django 3.2.3 on 2021-06-03 23:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_auto_20210603_2108"),
    ]

    operations = [
        migrations.RenameField(
            model_name="girderimage",
            old_name="accession_id",
            new_name="accession",
        ),
        migrations.AlterField(
            model_name="girderimage",
            name="dataset",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="images",
                to="core.girderdataset",
            ),
        ),
        migrations.AlterField(
            model_name="girderimage",
            name="file_id",
            field=models.CharField(
                editable=False,
                max_length=24,
                unique=True,
                validators=[django.core.validators.RegexValidator("^[0-9a-f]{24}$")],
            ),
        ),
        migrations.AlterField(
            model_name="girderimage",
            name="item_id",
            field=models.CharField(
                editable=False,
                max_length=24,
                unique=True,
                validators=[django.core.validators.RegexValidator("^[0-9a-f]{24}$")],
            ),
        ),
        migrations.AlterField(
            model_name="girderimage",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name="girderimage",
            name="original_blob_dm",
            field=models.CharField(
                editable=False,
                max_length=64,
                validators=[django.core.validators.RegexValidator("^[0-9a-f]{64}$")],
            ),
        ),
        migrations.AlterField(
            model_name="girderimage",
            name="original_file_relpath",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="girderimage",
            name="original_filename",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="girderimage",
            name="stripped_blob_dm",
            field=models.CharField(
                editable=False,
                max_length=64,
                validators=[django.core.validators.RegexValidator("^[0-9a-f]{64}$")],
            ),
        ),
        migrations.AlterField(
            model_name="girderimage",
            name="unstructured_metadata",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name="girderimage",
            name="accession",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ingest.accession",
            ),
        ),
    ]
