# Generated by Django 5.1.5 on 2025-03-06 03:49

from django.db import migrations, models
import django.db.models.deletion
import s3_file_field.fields

import isic.core.models.doi


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_doi_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doi",
            name="bundle",
            field=models.FileField(
                blank=True, null=True, upload_to=isic.core.models.doi.doi_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="doi",
            name="metadata",
            field=models.FileField(
                blank=True, null=True, upload_to=isic.core.models.doi.doi_upload_to
            ),
        ),
        migrations.CreateModel(
            name="SupplementalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", s3_file_field.fields.S3FileField()),
                ("description", models.CharField(max_length=255)),
                ("filename", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                (
                    "doi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplemental_files",
                        to="core.doi",
                    ),
                ),
            ],
        ),
    ]
