# Generated by Django 5.1.5 on 2025-03-12 15:03

from django.db import migrations, models

import isic.core.models.doi


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_doi_bundle_alter_doi_metadata_supplementalfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doi",
            name="bundle",
            field=models.FileField(
                blank=True,
                null=True,
                storage=isic.core.models.doi.doi_storage,
                upload_to=isic.core.models.doi.doi_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="doi",
            name="metadata",
            field=models.FileField(
                blank=True,
                null=True,
                storage=isic.core.models.doi.doi_storage,
                upload_to=isic.core.models.doi.doi_upload_to,
            ),
        ),
    ]
