# Generated by Django 5.1.5 on 2025-03-15 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_doi_schema_org_dataset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.CheckConstraint(
                condition=models.Q(("pinned", False), ("public", True), _connector="OR"),
                name="collection_pinned_are_public",
            ),
        ),
    ]
