# Generated by Django 3.2.3 on 2021-06-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210604_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girderimage',
            name='status',
            field=models.CharField(
                choices=[
                    ('unknown', 'Unknown'),
                    ('non_image', 'Non-Image'),
                    ('corrupt', 'Corrupt'),
                    ('migrated', 'Migrated'),
                    ('true_duplicate', 'True Duplicate'),
                ],
                default='unknown',
                max_length=30,
            ),
        ),
    ]
