# Generated by Django 5.1.7 on 2025-03-26 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_doi_schema_org_dataset"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supplementalfile",
            old_name="file",
            new_name="blob",
        ),
    ]
