# Generated by Django 5.1.8 on 2025-05-12 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_rename_file_supplementalfile_blob"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE core_collection_images RENAME TO core_collectionimage",
                    reverse_sql="ALTER TABLE core_collectionimage RENAME TO core_collection_images",
                    elidable=True,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="CollectionImage",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("created", models.DateTimeField(auto_now_add=True)),
                        (
                            "collection",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, to="core.collection"
                            ),
                        ),
                        (
                            "image",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, to="core.image"
                            ),
                        ),
                    ],
                    options={
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("collection", "image"),
                                name="collectionimage_collection_image_unique",
                            )
                        ],
                    },
                ),
                migrations.AlterField(
                    model_name="collection",
                    name="images",
                    field=models.ManyToManyField(
                        related_name="collections",
                        through="core.CollectionImage",
                        to="core.Image",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="collectionimage",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
