# Generated by Django 3.2.3 on 2021-06-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0018_auto_20210607_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='girderimage',
            name='pre_review',
            field=models.BooleanField(null=True),
        ),
    ]
