# Generated by Django 3.2.4 on 2021-08-07 02:28
from __future__ import annotations

import time

from django.conf import settings
from django.db import migrations
import requests

from isic.core.search import maybe_create_index


def _block_until_elasticsearch_is_available():
    time_slept = 0

    while True:
        try:
            requests.get(f"{settings.ISIC_ELASTICSEARCH_URI}/_cluster/health", timeout=1)
        except requests.exceptions.ConnectionError:
            time.sleep(1)
            time_slept += 1

            if time_slept > 30:
                raise TimeoutError("Elasticsearch did not become available in time")  # noqa: B904
        else:
            break


def create_elasticsearch_index(apps, schema_editor):
    _block_until_elasticsearch_is_available()
    maybe_create_index()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_auto_20210809_2143"),
    ]

    operations = [migrations.RunPython(create_elasticsearch_index)]
