# Generated by Django 3.2.4 on 2021-08-07 02:28

from django.db import migrations

from isic.core.search import maybe_create_index


def create_elasticsearch_index(apps, schema_editor):
    maybe_create_index()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210809_2143'),
    ]

    operations = [migrations.RunPython(create_elasticsearch_index)]
