# Generated by Django 5.1.9 on 2025-05-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_remove_collection_new_images_alter_collection_images"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplementalfile",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="supplementalfile",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
