# Generated by Django 5.1.9 on 2025-05-27 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_supplementalfile_options_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
CREATE MATERIALIZED VIEW IF NOT EXISTS materialized_collection_counts AS
SELECT
    ci.collection_id AS id,
    COUNT(DISTINCT ingest_accession.lesion_id) AS lesion_count,
    COUNT(DISTINCT ingest_accession.patient_id) AS patient_count,
    COUNT(ci.image_id) AS image_count
FROM core_collectionimage AS ci
INNER JOIN core_image ON ci.image_id = core_image.id
INNER JOIN ingest_accession ON core_image.accession_id = ingest_accession.id
GROUP BY 1;

-- a unique index is necessary to be able to refresh the materialized view concurrently
CREATE UNIQUE INDEX IF NOT EXISTS materialized_collection_counts_id_idx ON materialized_collection_counts (id);
            """,  # noqa: E501
            elidable=False,
        ),
    ]
