# Generated by Django 5.1.9 on 2025-05-27 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_materialized_view_collection_counts"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionCount",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="cached_counts",
                        serialize=False,
                        to="core.collection",
                    ),
                ),
                ("lesion_count", models.PositiveIntegerField()),
                ("patient_count", models.PositiveIntegerField()),
                ("image_count", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "materialized_collection_counts",
                "managed": False,
            },
        ),
    ]
