# Generated by Django 5.1.9 on 2025-06-03 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_collectioncount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"get_latest_by": "created", "ordering": ["created"]},
        ),
    ]
