# Generated by Django 5.1.9 on 2025-06-06 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_collection_description_squashed_0023_alter_image_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.CheckConstraint(
                condition=models.Q(("pinned", False), ("public", True), _connector="OR"),
                name="collection_pinned_implies_public",
            ),
        ),
    ]
