# Generated by Django 5.2.3 on 2025-06-28 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_collection_collection_pinned_implies_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="shares",
            field=models.ManyToManyField(
                related_name="collection_shares",
                through="core.CollectionShare",
                through_fields=("collection", "grantee"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="shares",
            field=models.ManyToManyField(
                through="core.ImageShare",
                through_fields=("image", "grantee"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
