# Generated by Django 3.2.6 on 2021-09-27 23:23
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_imageredirect_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagealias",
            options={"verbose_name_plural": "Image aliases"},
        ),
    ]
