# Generated by Django 5.2.3 on 2025-08-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_invert_doi_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoiRelatedIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("IsReferencedBy", "Is Referenced By"),
                            ("IsSupplementedBy", "Is Supplemented By"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "related_identifier_type",
                    models.CharField(choices=[("DOI", "DOI"), ("URL", "URL")], max_length=10),
                ),
                ("related_identifier", models.CharField(max_length=500)),
                (
                    "doi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_identifiers",
                        to="core.doi",
                    ),
                ),
            ],
            options={
                "verbose_name": "DOI Related Identifier",
                "verbose_name_plural": "DOI Related Identifiers",
                "unique_together": {
                    ("doi", "relation_type", "related_identifier_type", "related_identifier")
                },
            },
        ),
    ]
