# Generated by Django 5.2.3 on 2025-07-24 22:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_invert_doi_fk"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IsicOAuthApplication",
        ),
    ]
