# Generated by Django 5.2.3 on 2025-08-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_doirelatedidentifier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doirelatedidentifier",
            options={},
        ),
        migrations.AlterField(
            model_name="doirelatedidentifier",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("IsReferencedBy", "Is Referenced By"),
                    ("IsSupplementedBy", "Is Supplemented By"),
                    ("IsDescribedBy", "Is Described By"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="doirelatedidentifier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("relation_type", "IsDescribedBy")),
                fields=("doi",),
                name="unique_isdescribedby_per_doi",
            ),
        ),
    ]
