# Generated by Django 3.2.9 on 2021-11-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_girderimage_raw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DuplicateImage',
        ),
    ]
