# Generated by Django 5.2.3 on 2025-08-12 16:41

from django.db import migrations, models


def set_existing_dois_as_published(apps, _):
    Doi = apps.get_model("core", "Doi")
    Doi.objects.update(is_draft=False)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_doirelatedidentifier_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doi",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            set_existing_dois_as_published,
            elidable=True,
        ),
    ]
