# Generated by Django 5.2.3 on 2025-08-21 21:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import s3_file_field.fields

import isic.core.models.doi


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_add_doi_is_draft"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftDoi",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=isic.core.models.doi._generate_random_doi_id,  # noqa: SLF001
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator("^\\d+\\.\\d+/\\d+$")],
                    ),
                ),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "bundle",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=isic.core.models.doi.doi_storage,
                        upload_to=isic.core.models.doi.doi_upload_to,
                    ),
                ),
                ("bundle_size", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "metadata",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=isic.core.models.doi.doi_storage,
                        upload_to=isic.core.models.doi.doi_upload_to,
                    ),
                ),
                ("metadata_size", models.PositiveIntegerField(blank=True, null=True)),
                ("citations", models.JSONField(blank=True, default=dict)),
                ("schema_org_dataset", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Draft DOI",
                "verbose_name_plural": "Draft DOIs",
            },
        ),
        migrations.CreateModel(
            name="DraftDoiRelatedIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("IsReferencedBy", "Is Referenced By"),
                            ("IsSupplementedBy", "Is Supplemented By"),
                            ("IsDescribedBy", "Is Described By"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "related_identifier_type",
                    models.CharField(choices=[("DOI", "DOI"), ("URL", "URL")], max_length=10),
                ),
                ("related_identifier", models.CharField(max_length=500)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DraftSupplementalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("blob", s3_file_field.fields.S3FileField()),
                ("description", models.CharField(max_length=255)),
                ("filename", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="doirelatedidentifier",
            name="unique_isdescribedby_per_doi",
        ),
        migrations.RemoveField(
            model_name="doi",
            name="is_draft",
        ),
        migrations.AddConstraint(
            model_name="doirelatedidentifier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("relation_type", "IsDescribedBy")),
                fields=("doi",),
                name="doirelatedidentifier_unique_isdescribedby_per_doi",
            ),
        ),
        migrations.AddField(
            model_name="draftdoi",
            name="collection",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="core.collection"
            ),
        ),
        migrations.AddField(
            model_name="draftdoi",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="draftdoirelatedidentifier",
            name="doi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_identifiers",
                to="core.draftdoi",
            ),
        ),
        migrations.AddField(
            model_name="draftsupplementalfile",
            name="doi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplemental_files",
                to="core.draftdoi",
            ),
        ),
        migrations.AddConstraint(
            model_name="draftdoirelatedidentifier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("relation_type", "IsDescribedBy")),
                fields=("doi",),
                name="draftdoirelatedidentifier_unique_isdescribedby_per_doi",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="draftdoirelatedidentifier",
            unique_together={
                ("doi", "relation_type", "related_identifier_type", "related_identifier")
            },
        ),
    ]
