# Generated by Django 3.2.9 on 2021-11-11 03:54
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0001_initial_squashed"),
        ("core", "0029_auto_20211110_0008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="girderimage",
            name="accession",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ingest.accession",
            ),
        ),
    ]
