# Generated by Django 5.2.3 on 2025-08-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_fix_materialized_view_empty_collections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftdoi",
            name="bundle",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="draftdoi",
            name="metadata",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
