# Generated by Django 3.2.9 on 2021-11-12 02:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0030_alter_girderimage_accession'),
    ]

    operations = [
        migrations.CreateModel(
            name='GirderSegmentation',
            fields=[
                (
                    'id',
                    models.CharField(
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator('^[0-9a-f]{24}$')],
                    ),
                ),
                ('created', models.DateTimeField()),
                ('mask', s3_file_field.fields.S3FileField(null=True)),
                ('meta', models.JSONField(default=dict)),
                (
                    'creator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'image',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to='core.image'
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GirderSegmentationReview',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField()),
                ('approved', models.BooleanField()),
                (
                    'skill',
                    models.CharField(
                        choices=[('novice', 'novice'), ('expert', 'expert')], max_length=6
                    ),
                ),
                (
                    'segmentation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reviews',
                        to='core.girdersegmentation',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
