# Generated by Django 5.2.3 on 2025-09-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_alter_draftdoi_bundle_alter_draftdoi_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftdoi",
            name="is_publishing",
            field=models.BooleanField(default=False),
        ),
    ]
