# Generated by Django 5.2.3 on 2025-10-17 17:53

from django.conf import settings
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_add_is_publishing_to_draftdoi"),
        ("ingest", "0035_alter_distinctnessmeasure_checksum"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
    ]
