# Generated by Django 5.2.3 on 2025-10-18 03:41

from django.conf import settings
from django.db import migrations, models
import pgvector.django.halfvec


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_pgvector"),
        ("ingest", "0035_alter_distinctnessmeasure_checksum"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="embedding",
            field=pgvector.django.halfvec.HalfVectorField(blank=True, dimensions=3584, null=True),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.CheckConstraint(
                condition=models.Q(("embedding__isnull", True), ("public", True), _connector="OR"),
                name="image_embedding_public_check",
            ),
        ),
    ]
