# Generated by Django 5.2.3 on 2025-10-18 16:11

from django.conf import settings
from django.db import migrations
import pgvector.django.indexes


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_image_embedding_image_image_embedding_public_check"),
        ("ingest", "0035_alter_distinctnessmeasure_checksum"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="SET maintenance_work_mem = '1GB';",
            reverse_sql="SET maintenance_work_mem = DEFAULT;",
            elidable=True,
        ),
        migrations.AddIndex(
            model_name="image",
            index=pgvector.django.indexes.IvfflatIndex(
                fields=["embedding"],
                lists=1000,
                name="image_embedding_ivfflat_idx",
                opclasses=["halfvec_l2_ops"],
            ),
        ),
    ]
