# Generated by Django 5.2.3 on 2025-10-24 05:25

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.halfvec
import pgvector.django.indexes


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_image_image_embedding_ivfflat_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageEmbedding",
            fields=[
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="embedding_relation",
                        serialize=False,
                        to="core.image",
                    ),
                ),
                ("embedding", pgvector.django.halfvec.HalfVectorField(dimensions=3584)),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.IvfflatIndex(
                        fields=["embedding"],
                        lists=1000,
                        name="imageembedding_embed_ivfflat",
                        opclasses=["halfvec_l2_ops"],
                    )
                ],
            },
        ),
    ]
