# Generated by Django 5.2.3 on 2025-10-24 05:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_add_image_embedding_table"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="image",
            name="image_embedding_public_check",
        ),
        migrations.RemoveIndex(
            model_name="image",
            name="image_embedding_ivfflat_idx",
        ),
        migrations.RemoveField(
            model_name="image",
            name="embedding",
        ),
    ]
