# Generated by Django 5.2.3 on 2025-10-24 06:20

from django.db import migrations
import pgvector.django.indexes


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_remove_image_embedding_field"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="imageembedding",
            name="imageembedding_embed_ivfflat",
        ),
        migrations.AddIndex(
            model_name="imageembedding",
            index=pgvector.django.indexes.IvfflatIndex(
                fields=["embedding"],
                lists=1000,
                name="imageembedding_embed_ivfflat",
                opclasses=["halfvec_cosine_ops"],
            ),
        ),
    ]
