# Generated by Django 5.2.3 on 2025-10-29 17:21

from django.db import migrations, models

import isic.core.models.supplemental_file


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_merge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplementalfile",
            name="blob",
            field=models.FileField(
                storage=isic.core.models.supplemental_file.supplemental_file_storage,
                upload_to=isic.core.models.supplemental_file.supplemental_file_upload_to,
            ),
        ),
    ]
