# Generated by Django 5.2.15 on 2026-07-02 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_alter_collection_creator_and_more"),
        ("ingest", "0043_alter_rcmcase_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="pinned",
            field=models.PositiveSmallIntegerField(
                blank=True, default=None, null=True, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(fields=["pinned", "created"], name="pinned_created_index"),
        ),
    ]
