# Generated by Django 5.2.15 on 2026-07-02 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_pinned_images"),
        ("ingest", "0043_alter_rcmcase_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="image",
            constraint=models.CheckConstraint(
                condition=models.Q(("pinned__isnull", True), ("public", True), _connector="OR"),
                name="image_pinned_implies_public",
            ),
        ),
    ]
