# Generated by Django 5.2.15 on 2026-07-02 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_image_image_pinned_implies_public"),
        ("ingest", "0043_alter_rcmcase_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="image",
            name="image_pinned_implies_public",
        ),
        migrations.AlterField(
            model_name="image",
            name="pinned",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.CheckConstraint(
                condition=models.Q(("pinned", 0), ("public", True), _connector="OR"),
                name="image_pinned_implies_public",
            ),
        ),
        migrations.RemoveIndex(
            model_name="image",
            name="pinned_created_index",
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(fields=["-pinned", "created"], name="pinned_created_index"),
        ),
    ]
