# Generated by Django 4.0.3 on 2022-05-25 16:02
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_isicoauthapplication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="isicoauthapplication",
            options={"verbose_name": "ISIC OAuth application"},
        ),
    ]
