# Generated by Django 5.2.15 on 2026-08-04 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_image_pin_nonnull"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "get_latest_by": "created",
                "ordering": ["created"],
                "permissions": (("view_image_metadata", "View Image Metadata"),),
            },
        ),
    ]
