# Generated by Django 5.2.15 on 2026-07-08 14:43

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_image_pin_nonnull"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tag", models.CharField(max_length=255)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("tag"), name="unique_lowercase_tag"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="tags",
            field=models.ManyToManyField(related_name="collections", to="core.collectiontag"),
        ),
    ]
