# Generated by Django 4.1.10 on 2023-08-16 03:47

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_doi_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segmentation",
            name="mask",
            field=s3_file_field.fields.S3FileField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
