# Generated by Django 4.1.10 on 2023-08-16 03:47
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_alter_segmentation_mask"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="segmentation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("mask", ""), _negated=True),
                fields=("mask",),
                name="segmentation_unique_mask",
            ),
        ),
    ]
