# Generated by Django 4.2.13 on 2024-06-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_segmentation_segmentation_unique_mask"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="collectionshare",
            constraint=models.UniqueConstraint(
                fields=("creator", "collection", "recipient"),
                name="collectionshare_creator_collection_recipient_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="imageshare",
            constraint=models.UniqueConstraint(
                fields=("creator", "image", "recipient"),
                name="imageshare_creator_image_recipient_unique",
            ),
        ),
    ]
