# Generated by Django 4.2.13 on 2024-06-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0049_collectionshare_collectionshare_creator_collection_recipient_unique_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="collectionshare",
            name="collectionshare_creator_recipient_diff_check",
        ),
        migrations.RemoveConstraint(
            model_name="collectionshare",
            name="collectionshare_creator_collection_recipient_unique",
        ),
        migrations.RemoveConstraint(
            model_name="imageshare",
            name="imageshare_creator_recipient_diff_check",
        ),
        migrations.RemoveConstraint(
            model_name="imageshare",
            name="imageshare_creator_image_recipient_unique",
        ),
        migrations.RenameField(
            model_name="collectionshare",
            old_name="recipient",
            new_name="grantee",
        ),
        migrations.RenameField(
            model_name="collectionshare",
            old_name="creator",
            new_name="grantor",
        ),
        migrations.RenameField(
            model_name="imageshare",
            old_name="recipient",
            new_name="grantee",
        ),
        migrations.RenameField(
            model_name="imageshare",
            old_name="creator",
            new_name="grantor",
        ),
        migrations.AddConstraint(
            model_name="collectionshare",
            constraint=models.CheckConstraint(
                check=models.Q(("grantor", models.F("grantee")), _negated=True),
                name="collectionshare_grantor_grantee_diff_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionshare",
            constraint=models.UniqueConstraint(
                fields=("grantor", "collection", "grantee"),
                name="collectionshare_grantor_collection_grantee_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="imageshare",
            constraint=models.CheckConstraint(
                check=models.Q(("grantor", models.F("grantee")), _negated=True),
                name="imageshare_grantor_grantee_diff_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="imageshare",
            constraint=models.UniqueConstraint(
                fields=("grantor", "image", "grantee"),
                name="imageshare_grantor_image_grantee_unique",
            ),
        ),
    ]
